AIRBASE_STATUS = {
    ["Abu al-Duhur"] = false,
    ["Adana Sakirpasa"] = true,
    ["Aleppo"] = true,
    ["Bassel Al-Assad"] = false,
    ["Gaziantep"] = true,
    ["Hatay"] = false,
    ["Incirlik"] = true,
    ["Jirah"] = false,
    ["Kharab Ishk"] = false,
    ["Kuweires"] = false,
    ["Minakh"] = false,
    ["Sanliurfa"] = false,
    ["Tabqa"] = false,
    ["Taftanaz"] = false,
    ["Tal Siman"] = false,
}