import fs from 'fs';
import path from 'path';

/**
 * CSV Parser - READ-ONLY OPERATIONS
 *
 * IMPORTANT: This module ONLY reads CSV files, never writes to them.
 * CSV files are generated by the DCS server and must NEVER be modified by this application.
 */

/**
 * Parse a CSV file with format: "item,quantity" (READ-ONLY)
 * @param {string} filePath - Path to CSV file
 * @returns {Array} Array of {item, quantity} objects
 */
export async function parseCSV(filePath) {
  try {
    // READ-ONLY: Only reading CSV files, never writing
    await fs.promises.access(filePath, fs.constants.F_OK);
    const content = await fs.promises.readFile(filePath, 'utf-8');
    const lines = content.split('\n').filter(line => line.trim());

    return lines.map(line => {
      const [item, quantity] = line.split(',').map(s => s.trim());
      return {
        item: item || 'unknown',
        quantity: parseInt(quantity) || 0,
      };
    }).filter(entry => entry.item && entry.item !== ''); // Filter empty items
  } catch (error) {
    if (error.code === 'ENOENT') {
      console.warn(`CSV file not found: ${filePath}`);
    } else {
      console.error(`Error parsing CSV ${filePath}:`, error.message);
    }
    return [];
  }
}

/**
 * Get all data for an airport
 * @param {string} csvPrefix - CSV filename prefix (e.g., "Adana Sakirpasa")
 * @param {string} dataDir - Directory containing CSV files
 * @returns {Object} Object with weapons and liquids data
 */
export async function getAirportData(csvPrefix, dataDir = './') {
  const weaponsPath = path.join(dataDir, `${csvPrefix}_weapons.csv`);
  const liquidsPath = path.join(dataDir, `${csvPrefix}_liquids.csv`);

  const [weapons, liquids] = await Promise.all([
    parseCSV(weaponsPath),
    parseCSV(liquidsPath)
  ]);

  return {
    weapons,
    liquids,
    timestamp: Date.now(),
  };
}

/**
 * Parse all airports data
 * @param {Array} airports - Array of airport configs
 * @param {string} dataDir - Directory containing CSV files
 * @returns {Object} Object with all airports data
 */
export async function parseAllAirports(airports, dataDir = './') {
  const entries = await Promise.all(airports.map(async (airport) => {
    try {
      const data = await getAirportData(airport.csvPrefix, dataDir);
      return [airport.id, { ...airport, data }];
    } catch (error) {
      console.error(`Error loading data for ${airport.name}:`, error.message);
      return [
        airport.id,
        {
          ...airport,
          data: { weapons: [], liquids: [], timestamp: Date.now() },
          error: error.message,
        }
      ];
    }
  }));

  return Object.fromEntries(entries);
}

export default {
  parseCSV,
  getAirportData,
  parseAllAirports,
};
