import fs from 'fs';
import path from 'path';

/**
 * CSV Parser - READ-ONLY OPERATIONS
 *
 * IMPORTANT: This module ONLY reads CSV files, never writes to them.
 * CSV files are generated by the DCS server and must NEVER be modified by this application.
 */

/**
 * Parse a CSV file with format: "item,quantity" (READ-ONLY)
 * @param {string} filePath - Path to CSV file
 * @returns {Array} Array of {item, quantity} objects
 */
export function parseCSV(filePath) {
  try {
    if (!fs.existsSync(filePath)) {
      console.warn(`CSV file not found: ${filePath}`);
      return [];
    }

    // READ-ONLY: Only reading CSV files, never writing
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.split('\n').filter(line => line.trim());

    return lines.map(line => {
      const [item, quantity] = line.split(',').map(s => s.trim());
      return {
        item: item || 'unknown',
        quantity: parseInt(quantity) || 0,
      };
    }).filter(entry => entry.item && entry.item !== ''); // Filter empty items
  } catch (error) {
    console.error(`Error parsing CSV ${filePath}:`, error.message);
    return [];
  }
}

/**
 * Get all data for an airport
 * @param {string} csvPrefix - CSV filename prefix (e.g., "Adana Sakirpasa")
 * @param {string} dataDir - Directory containing CSV files
 * @returns {Object} Object with weapons and liquids data
 */
export function getAirportData(csvPrefix, dataDir = './') {
  const weaponsPath = path.join(dataDir, `${csvPrefix}_weapons.csv`);
  const liquidsPath = path.join(dataDir, `${csvPrefix}_liquids.csv`);

  const weapons = parseCSV(weaponsPath);
  const liquids = parseCSV(liquidsPath);

  return {
    weapons,
    liquids,
    timestamp: Date.now(),
  };
}

/**
 * Parse all airports data
 * @param {Array} airports - Array of airport configs
 * @param {string} dataDir - Directory containing CSV files
 * @returns {Object} Object with all airports data
 */
export function parseAllAirports(airports, dataDir = './') {
  const result = {};

  airports.forEach(airport => {
    try {
      result[airport.id] = {
        ...airport,
        data: getAirportData(airport.csvPrefix, dataDir),
      };
    } catch (error) {
      console.error(`Error loading data for ${airport.name}:`, error.message);
      result[airport.id] = {
        ...airport,
        data: { weapons: [], liquids: [], timestamp: Date.now() },
        error: error.message,
      };
    }
  });

  return result;
}

export default {
  parseCSV,
  getAirportData,
  parseAllAirports,
};
