const metaIt = {
  name: 'Nome',
  nickname: 'Soprannome',
  age: 'Età',
  nationality: 'Nazionalità',
  origin: 'Origine',
  faction: 'Fazione',
  role: 'Ruolo',
  category: 'Categoria',
  association: 'Associazione',
};

const metaEn = {
  name: 'Name',
  nickname: 'Nickname',
  age: 'Age',
  nationality: 'Nationality',
  origin: 'Origin',
  faction: 'Faction',
  role: 'Role',
  category: 'Category',
  association: 'Association',
};

const sectionsIt = {
  profile: 'Profilo',
  personality: 'Personalità',
  appearance: 'Aspetto',
  network: 'Dispositivo operativo',
  relationships: 'Relazioni',
  weakness: 'Valutazione della minaccia',
  treeLink: 'Recap operativo',
};

const sectionsEn = {
  profile: 'Profile',
  personality: 'Personality',
  appearance: 'Appearance',
  network: 'Operational picture',
  relationships: 'Relationships',
  weakness: 'Threat assessment',
  treeLink: 'Operational recap',
};

function meta(labels, values) {
  return Object.fromEntries(
    Object.keys(values).map((key) => [key, { label: labels[key], value: values[key] }]),
  );
}

export const lidcWhiteboardItemsIt = {
  samiullahBarakzai: {
    label: 'Sangsar',
    title: 'Maulvi Samiullah Barakzai — "Sangsar"',
    meta: meta(metaIt, {
      name: 'Samiullah Barakzai',
      nickname: '"Sangsar" — La Roccia',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Distretto di Panjwai, Kandahar',
      faction: 'Talebani — Shura-ye-Sangsar',
      role: 'Giudice e coordinatore politico-religioso',
      category: 'Direzione politico-religiosa',
      association: 'Ex tribunale distrettuale occupato, Kandahar',
    }),
    sections: sectionsIt,
    profile: 'Samiullah viene da una famiglia di mullah di Panjwai, non da una famiglia di comandanti. Ha studiato in madrasa a Kandahar e per anni ha scritto sentenze su terre, debiti e faide, senza mai guidare un’imboscata. Gli altri capi della rete lo accettano a presiedere proprio per questo: non chiede il comando dei combattenti.\n\nPresiede la Shura-ye-Sangsar, il consiglio politico-religioso che tiene insieme i cinque rami della rete talebana locale: il consiglio stesso, la tesoreria di Abdul Rahman, i combattenti di Omar Hakimi, la propaganda e il reclutamento (Faisal Noor e Hamidullah Safi) e la logistica di Bashir Achakzai. Chi ignora il consiglio, almeno sulla carta, perde i soldi di Rahman e le reclute di Safi. Non dà ordini di fuoco a Hakimi: il suo lavoro è far sì che quei cinque rami restino una sola organizzazione.',
    personality: 'È lento, formale e vanitoso da religioso. Parla poco, corregge gli altri e non alza la voce. Gli stranieri, per lui, non sono un bersaglio da colpire: sono un problema da tenere fuori dal complesso dove giudica. Viktor Sokolov, il contatto russo sulle armi, non deve metterci piede. Teme una sentenza sbagliata più di un attacco aereo, perché una sentenza sbagliata gli fa perdere i capivillaggio.',
    appearanceItems: [
      'Resta quasi sempre nel recinto dell’ex tribunale distrettuale, il palazzo governativo occupato a sud-ovest di Kandahar da cui presiede il consiglio',
      'Non porta armi lunghe',
      'Due o tre uomini armati al cancello del recinto, non una guarnigione',
      'Non usa il telefono satellitare',
      'Sentenze scritte a mano, affisse nel cortile interno del palazzo',
    ],
    networkSteps: [
      'Ex tribunale distrettuale occupato — sud-ovest di Kandahar città',
      'Recinto, cortile, stanza delle udienze',
      'Antenna da tetto civile (resto del palazzo, non un ripetitore militare)',
      'Messaggeri a piedi; rapporti informativi tramite Rahmatullah Hotak',
    ],
    networkNote: 'Sul tetto è rimasta l’antenna televisiva/radio del palazzo. Serve solo a chiamate corte nel raggio della città: non è collegata alla rete radio di propaganda di Faisal Noor. Rahman, tesoriere, viene ricevuto nel recinto ogni tanto. Hakimi, capo dei combattenti, quasi mai. Faisal Noor non entra nel complesso: la sua voce è già riconoscibile in radio, e il palazzo non deve bruciarsi con lui.',
    relationshipItems: [
      'Rahmatullah Hotak — capo dei servizi informativi (Daftar-e-Khabar). Raccoglie le informazioni al posto suo. In cambio ottiene la protezione del consiglio.',
      'Abdul Rahman — porta i soldi dell’ushr, la decima religiosa sui raccolti. Samiullah dà alla tesoreria un riconoscimento religioso.',
      'Omar Hakimi — comanda i combattenti. Il giudice copre le operazioni con le sentenze; non gli dà gli ordini di fuoco.',
      'Faisal Noor — propagandista radio. Prende le sentenze affisse nel cortile e le legge in antenna. Samiullah lo trova volgare, ma sa che la radio arriva più lontano di un muro.',
      'Hamidullah Safi — reclutatore. Samiullah lo benedice in pubblico: i ragazzi arrivano alle cellule con il riconoscimento del consiglio.',
    ],
    weakness: 'Non pianifica imboscate. Se resta al suo posto i cinque rami restano una rete. Se viene a mancare, tesoreria, combattenti, propaganda e logistica tornano a lavorare ognuno per sé.',
    treeLinkSteps: [
      'Shura-ye-Sangsar',
      'Samiullah Barakzai',
      'Copertura religiosa',
      'Cinque rami tenuti insieme',
    ],
    treeLinkNote: 'Senza Samiullah i cinque rami restano cinque mestieri uno accanto all’altro. Non è un comandante militare, ma tiene insieme l’organizzazione sul piano politico.',
  },
  rahmatullahHotak: {
    label: 'Karg',
    title: 'Rahmatullah Hotak — "Karg"',
    meta: meta(metaIt, {
      name: 'Rahmatullah Hotak',
      nickname: '"Karg" — Il Corvo',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Distretto di Arghandab, Kandahar',
      faction: 'Talebani — Shura-ye-Sangsar / Daftar-e-Khabar',
      role: 'Capo dei servizi informativi',
      category: 'Intelligence',
      association: 'Unico contatto talebano della fonte Farid Ahmad Khan',
    }),
    sections: sectionsIt,
    profile: 'Hotak è cresciuto ad Arghandab facendo il corriere e poi l’informatore. Non ha mai guidato una cellula armata. I pastori lo chiamano Karg perché lo vedono sulle creste sopra la valle e poi non c’è più.\n\nDirige il Daftar-e-Khabar, l’ufficio informazioni della Shura-ye-Sangsar, il consiglio di Samiullah Barakzai. È l’unico talebano autorizzato a gestire Farid Ahmad Khan, una fonte pagata: non come un amico, come una merce. Quello che Farid vende — movimenti, orari, posti di blocco — diventa preavvisi per Omar Hakimi, capo dei combattenti, e indicazioni di percorso per Bashir Achakzai, che muove i convogli.',
    personality: 'È taciturno, sospettoso, quasi superstizioso. Conta le cose. Non alza la voce e non fa discorsi. Non sopporta chi fa rumore, Faisal Noor per primo, il propagandista radio. Con Farid il rapporto è sporco: lo paga, lo tiene sotto ricatto, non lo stima.',
    appearanceItems: [
      'Berretto pakol di lana, non turbante',
      'Binocolo, taccuino, piccolo ripetitore radio a bassa potenza',
      'Evita la via principale che taglia Arghandab',
      'Il ripetitore resta spento negli stessi orari in cui Farid risulta in servizio',
    ],
    networkSteps: [
      'Posto di osservazione «Cresta Karg» — colline a nord-ovest di Arghandab',
      'Riparo in pietra, telo, ripetitore basso (segnale corto, non la rete di Faisal)',
      'In città: un venditore di telefoni usati fa da intermediario',
      'Dorme a valle, in una casa sicura, non sulla cresta',
    ],
    networkNote: 'Hotak e Farid non si trovano mai nella stessa stanza. Il venditore di telefoni passa i messaggi e i pagamenti. Il ripetitore sulla cresta serve solo a sentire e a far arrivare un avviso a breve raggio: non è un ponte verso la radio di propaganda. La coincidenza tra ripetitore spento e orari di Farid suggerisce che Hotak non vuole emettere mentre la fonte è esposta.',
    relationshipItems: [
      'Samiullah Barakzai — unico superiore, giudice e presidente del consiglio. Hotak gli porta le notizie già selezionate, non il grezzo.',
      'Farid Ahmad Khan — fonte più utile e più sporca. Una fotografia di sorveglianza, Farid ripreso dove non dovrebbe, usata come ricatto.',
      'Omar Hakimi — capo dei combattenti. Riceve avvisi già puliti, spesso senza sapere da dove arrivano.',
      'Bashir Achakzai — responsabile dei convogli. Compra indicazioni sui posti di blocco; in cambio passa i movimenti dei camion.',
      'Nazar Mohammad Alizai (Tufan) — batteria AAA / MANPADS a sud di Kandahar. Hotak non gli passa gli osservatori: una cresta che spara e una fonte pagata non devono coincidere.',
    ],
    weakness: 'Minaccia di informazioni, non di fuoco. Senza di lui i combattenti restano armati, ma Hakimi perde i preavvisi e Bashir perde le strade già lette. Il consiglio resta cieco.',
    treeLinkSteps: [
      'Farid Ahmad Khan (fonte pagata)',
      'Rahmatullah Hotak',
      'Shura-ye-Sangsar',
      'Preavvisi a Hakimi e Bashir',
    ],
    treeLinkNote: 'È il ponte tra Farid Khan e i Talebani. Senza di lui la fonte non ha un destinatario utile, e il consiglio perde le informazioni.',
  },
  hamidullahSafi: {
    label: 'Ustad',
    title: 'Hamidullah Safi — "Ustad"',
    meta: meta(metaIt, {
      name: 'Hamidullah Safi',
      nickname: '«Ustad», tra i ragazzi',
      age: '29 anni',
      nationality: 'Afghana',
      origin: 'Distretto di Khakrez, Kandahar',
      faction: 'Talebani — Sada-ye-Maiwand',
      role: 'Reclutatore',
      category: 'Reclutamento',
      association: 'Madrasa di villaggio a Khakrez — reclutamento, non addestramento',
    }),
    sections: sectionsIt,
    profile: 'Safi ha ventinove anni. I ragazzi lo chiamano Ustad, “maestro”, perché parla come un insegnante di cortile, non come un comandante. Figlio di un imam di villaggio a Khakrez, ha imparato a convincere i ragazzini prima che a sparare. Non è un propagandista: non sta al microfono. Non è un capo combattenti: non tiene una cellula. Porta i ragazzi fino al cancello della lashkar e poi li lascia ad altri.\n\nTrova, convince, sposta. Lavora su debiti di famiglia, vendette, fame e orgoglio. Abdul Rahman, tesoriere, paga le famiglie perché lascino partire i figli. Ha rifiutato di diventare la seconda voce di Faisal Noor, il propagandista radio, perché la radio lo brucerebbe.',
    personality: 'È carismatico in modo giovane, non teatrale come Faisal. Crede in quello che dice più di Rahman e meno di Samiullah Barakzai, il giudice. Si infastidisce se lo chiamano soldato. Ha paura di Rahmatullah Hotak, capo dei servizi informativi: una lista di nomi in quelle mani è una condanna.',
    appearanceItems: [
      'Giovane, barba nera',
      'Gilet nero su kameez bianco (tunica lunga)',
      'Niente turbante',
      'Niente armi lunghe nella madrasa',
      'Furgone bianco con un paraurti riparato: ci sposta i ragazzi quando il villaggio è quieto',
    ],
    networkSteps: [
      'Madrasa «Cortile Safi» — nord di Kandahar, distretto di Khakrez',
      'Edificio a un piano, albero, recinto: lezioni nel cortile, non un campo di tiro',
      'Partenze di notte o all’alba, quando il villaggio non guarda',
      'Le armi arrivano dopo, dalle cellule di Omar Hakimi',
    ],
    networkNote: 'Non è un campo di addestramento: qui si parla e si parte. Evita Gereshk e l’Helmand, la zona della tesoreria, perché lì i ragazzi finiscono nei campi di oppio di Rahman invece che nelle cellule di Hakimi.',
    relationshipItems: [
      'Faisal Noor — stesso ramo, Sada-ye-Maiwand (propaganda e reclutamento), non è il suo capo. La radio di Faisal prepara i villaggi; il cortile di Safi raccoglie chi si alza.',
      'Omar Hakimi — capo dei combattenti. È dove finiscono i ragazzi. In cambio Safi ottiene che non finiscano a zappare l’oppio.',
      'Abdul Rahman — tesoriere. Paga le famiglie. Safi odia che quei soldi vengano dall’oppio, ma li prende.',
      'Samiullah Barakzai — giudice e presidente del consiglio. Lo benedice in pubblico e in privato lo trova troppo acceso.',
    ],
    weakness: 'Minaccia di uomini nuovi, non di fuoco. Se la madrasa si chiude, si ferma il flusso di reclute verso Hakimi. Faisal resta a parlare a una rete che non si rinnova.',
    treeLinkSteps: [
      'Sada-ye-Maiwand (propaganda / reclutamento)',
      'Hamidullah Safi',
      'Madrasa di Khakrez',
      'Reclute verso Hakimi',
    ],
    treeLinkNote: 'Senza Safi, Hakimi consuma i villaggi e Faisal parla a una rete che non si rinnova.',
  },
  zahirPopalzai: {
    label: 'Shisha',
    title: 'Zahir Popalzai — "Shisha"',
    meta: meta(metaIt, {
      name: 'Zahir Popalzai',
      nickname: '"Shisha"',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Nord di Lashkar Gah, Helmand',
      faction: 'Talebani — Bayt al-Mal-e-Helmand',
      role: 'Supervisore del laboratorio clandestino',
      category: 'Tesoreria / trasformazione',
      association: 'Laboratorio a nord di Lashkar Gah — trasformazione, non coltivazione',
    }),
    sections: sectionsIt,
    profile: 'Zahir non è un signore dell’oppio. È un ex insegnante di chimica di Lashkar Gah. Abdul Rahman, tesoriere, lo ha preso perché sa pesare e tagliare, non perché sa sparare. Il soprannome Shisha viene dai tubi di vetro del laboratorio, come quelli di un narghilè.\n\nÈ l’unico responsabile della trasformazione nella tesoreria, il ramo Bayt al-Mal-e-Helmand. Dai campi arriva pasta d’oppio grezza; Zahir la lavora e restituisce un prodotto già raffinato, che vale di più. Non comanda i campi e non porta i carichi al confine.',
    personality: 'È ansioso e istruito. Non è un ideologo. Ha più paura di Rahman che della coalizione. Fuma in continuazione, dita gialle. Samiullah Barakzai, il giudice, lo considera impuro per l’oppio: quella distanza la vogliono sia Rahman sia il consiglio. Il laboratorio deve restare invisibile perché, in pubblico, la tesoreria resti accettabile.',
    appearanceItems: [
      'Cuffia da preghiera, niente turbante',
      'Dita gialle di nicotina',
      'Esce di rado dal recinto della casa-laboratorio',
      'Quaderni di scuola per i pesi e le dosi',
    ],
    networkSteps: [
      'Laboratorio «Casa Shisha» — nord di Lashkar Gah, Helmand',
      'Casa recintata tra i campi di oppio e un canale',
      'Teli di plastica, bidoni, generatore, fossa di scarico: lavorazione, non magazzino di armi',
      'Due aiutanti, non armati',
    ],
    networkNote: 'Rahman non entra: manda un cugino a ritirare il prodotto. Omar Hakimi, capo dei combattenti, non sa esattamente dove sia. I campi coltivano; il laboratorio trasforma. Sono due siti diversi, e devono restare tali.',
    relationshipItems: [
      'Abdul Rahman — tesoriere e padrone. Zahir gli deve casa e soldi; Rahman gli deve il guadagno extra che i campi, da soli, non fanno.',
      'Bashir Achakzai — responsabile dei convogli. Ha portato solvente e fatto troppe domande. Ora i contenitori arrivano come merce di magazzino, senza che gli autisti sappiano cosa c’è dentro.',
      'Samiullah Barakzai — giudice. Non lo riceve nel tribunale. In pubblico la tesoreria resta accettabile solo perché il laboratorio resta fuori dalla vista del consiglio.',
    ],
    weakness: 'Minaccia indiretta, attraverso i soldi. Un colpo al laboratorio non ferma i fucili il giorno dopo, ma taglia il guadagno di Rahman e ritarda gli stipendi di Hakimi, Faisal Noor e Hamidullah Safi.',
    treeLinkSteps: [
      'Campi di oppio di Rahman',
      'Zahir Popalzai',
      'Laboratorio a Lashkar Gah',
      'Denaro per Hakimi, Faisal, Safi',
    ],
    treeLinkNote: 'Senza di lui la tesoreria vende pasta d’oppio grezza: meno guadagno, più gente in mezzo, stipendi più lenti.',
  },
  nazarMohammadAlizai: {
    label: 'Tufan',
    title: 'Nazar Mohammad Alizai — "Tufan"',
    meta: meta(metaIt, {
      name: 'Nazar Mohammad Alizai',
      nickname: '"Tufan" — Tempesta',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Distretto di Dand, Kandahar',
      faction: 'Talebani — Lashkar-e-Maiwand',
      role: 'Responsabile della contraerea',
      category: 'Difesa aerea tattica',
      association: 'Batteria AAA / MANPADS — cresta a sud di Kandahar',
    }),
    sections: sectionsIt,
    profile: 'Alizai ha fatto il mitragliere su veicoli scoperti per anni. Un elicottero gli ha ucciso il fratello; da allora il cielo è il suo lavoro. Omar Hakimi, capo dei combattenti, lo ha tolto dalle imboscate perché a terra sprecava munizioni e contro gli aerei le usava bene.\n\nÈ l’unico referente della Lashkar-e-Maiwand, il ramo armato, per la minaccia aerea a bassa quota. Tiene AAA trainata, mitragliere pesanti e pochi MANPADS. I missili gli arrivano da Hakimi; Tufan non sa con certezza che dietro c’è Viktor Sokolov, il contatto russo sulle armi.',
    personality: 'È testardo, rancoroso e semplice. Tratta il cielo come un nemico personale. Rispetta Hakimi perché gli ha dato i missili. Invidia Faisal Noor, il propagandista radio, la cui voce arriva lontano senza farsi sparare. Mastica naswar, tabacco da bocca. Prega guardando in su.',
    appearanceItems: [
      'Niente turbante',
      'Giacca mimetica sopra il kameez (tunica lunga)',
      'Sguardo stretto, spesso contro luce, a cercare velivoli',
      'Sposta i pezzi AAA in un raggio breve intorno alla cresta, per non restare un bersaglio fisso',
    ],
    networkSteps: [
      'Batteria «Cresta Tufan» — sud di Kandahar',
      'AAA trainata, sacchi di terra, teloni',
      'Veicolo con mitragliatrice pesante',
      'Nascondigli per i MANPADS e pezzi finti (decoy)',
    ],
    networkNote: 'Usa osservatori suoi a valle della Cresta Tufan, non la rete di Rahmatullah Hotak (Cresta Karg, Arghandab). Zone diverse; si evitano lo stesso: Hotak non vuole la batteria legata alla fonte, Tufan non vuole uomini dei servizi intorno ai MANPADS. Dorme in una cava a mezza costa, non sulla linea dei pezzi.',
    relationshipItems: [
      'Omar Hakimi — capo dei combattenti. Gli ha dato questo mestiere e i MANPADS. Senza Tufan, Hakimi muove uomini visibili dagli elicotteri.',
      'Viktor Sokolov — contatto russo. Tufan non lo ha mai incontrato. I MANPADS arrivano come «roba dei fratelli», senza spiegare la provenienza.',
      'Bashir Achakzai — responsabile dei convogli. I suoi camion alzano polvere e coprono la vista del cielo. Conflitto di mestiere, non una faida da consiglio.',
    ],
    weakness: 'Minaccia aerea diretta: AAA e MANPADS. Nessun peso politico. Senza la batteria, l’ex tribunale di Samiullah, le torri radio di Faisal e i rifugi della rete restano più esposti a chi vola basso.',
    treeLinkSteps: [
      'Lashkar-e-Maiwand (combattenti)',
      'Nazar Mohammad Alizai',
      'Cresta Tufan',
      'Volare bassi su Kandahar costa di più',
    ],
    treeLinkNote: 'Il suo lavoro rende costoso volare bassi su Kandahar, sulle torri radio di Faisal e sul tribunale occupato di Samiullah.',
  },
  izatullahNoorzai: {
    label: 'Khatar',
    title: 'Izatullah Noorzai — "Khatar"',
    meta: meta(metaIt, {
      name: 'Izatullah Noorzai',
      nickname: '"Khatar" — Pericolo',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Distretto di Gereshk, Helmand',
      faction: 'Talebani — Lashkar-e-Maiwand',
      role: 'Responsabile delle mine e degli IED',
      category: 'Guerra mine',
      association: 'Officina IED a ovest di Gereshk',
    }),
    sections: sectionsIt,
    profile: 'Noorzai è un meccanico di strada. Il soprannome Khatar, “pericolo”, gli è rimasto dopo che una mina gli ha portato via due dita della mano sinistra: ha imparato a costruirle restando sotto. Omar Hakimi, capo dei combattenti, gli ha vietato di comandare una cellula dopo che un suo gruppo ha fatto saltare il veicolo sbagliato.\n\nNella Lashkar-e-Maiwand, il ramo armato, produce cariche, inneschi, mine anticarro artigianali e trappole. Non decide dove colpire. Riceve un segno su una mappa da un uomo di Hakimi e prepara l’ordigno. I combattenti lo mettono a terra. Lui lo costruisce.',
    personality: 'È irritabile, superstizioso e scortese. Ce l’ha con Hakimi per avergli tolto gli uomini, ma obbedisce. Non sopporta Zahir Popalzai, il chimico del laboratorio di oppio: l’odore di quella casa gli ricorda i fumi sbagliati. Non vuole inneschi arrivati dalla rete di Viktor Sokolov, il contatto russo.',
    appearanceItems: [
      'Mano sinistra mutilata (due dita in meno)',
      'Non porta turbante',
      'Bruciatura sul collo',
      'Generatore udibile quando è acceso, nell’officina',
    ],
    networkSteps: [
      'Officina «Fattoria Khatar» — ovest di Gereshk, Helmand',
      'Capannone: batterie, cavi, fertilizzante, generatore',
      'Spostamento su motocarro, carichi corti',
      'Comunicazione con biglietti, non radio: niente firma elettromagnetica',
    ],
    networkNote: 'Evita i convogli di carburante di Bashir Achakzai quando può: un sequestro sulla Hwy 1 non deve portare agli inneschi. Qualche cassa, a pagamento, può viaggiare tra i ricambi. Il materiale non resta a lungo in capannone: esce verso le cellule di Hakimi.',
    relationshipItems: [
      'Omar Hakimi — capo dei combattenti e superiore. Gli ha tolto gli uomini e gli ha lasciato il bancone, le mappe e chi pianta gli ordigni.',
      'Bashir Achakzai — responsabile dei convogli. A pagamento gli nasconde qualche cassa tra i ricambi, e può rifiutare quando il rischio di sequestro è alto.',
      'Abdul Rahman — tesoriere. Paga Hakimi, Hakimi paga Khatar. Izatullah non vuole l’oppio vicino al fertilizzante.',
    ],
    weakness: 'Pericoloso per chi si muove a terra e per elicotteri a bassa quota sulle stesse piste. L’officina, da sola, dall’aria è un bersaglio molle. Hakimi può sostituirlo, ma non in fretta.',
    treeLinkSteps: [
      'Lashkar-e-Maiwand (combattenti)',
      'Izatullah Noorzai',
      'Officina IED a Gereshk',
      'Piste pericolose senza imboscata',
    ],
    treeLinkNote: 'Importante sul terreno, irrilevante in politica. Se viene meno, la lashkar perde chi rende pericolose le strade anche dove non c’è un’imboscata.',
  },
  bashirAchakzai: {
    label: 'Karwan',
    title: 'Bashir Achakzai — "Karwan"',
    meta: meta(metaIt, {
      name: 'Bashir Achakzai',
      nickname: '"Karwan" — La Carovana',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Fascia Achakzai di Spin Boldak, Kandahar',
      faction: 'Talebani — Karwan-e-Dasht',
      role: 'Responsabile dei convogli',
      category: 'Logistica',
      association: 'Convogli su Hwy 1 e piste — carburante, viveri, ricambi; non oppio, non casse Sokolov',
    }),
    sections: sectionsIt,
    profile: 'Bashir è un mercante prima che un talebano. Gli Achakzai, dalla fascia di Spin Boldak, tengono le strade. Lui tiene i camion. Dirige il Karwan-e-Dasht, il ramo logistico della rete. Abdul Rahman, tesoriere, lo ha preso perché i suoi autisti non fanno domande. Omar Hakimi, capo dei combattenti, lo usa perché una cellula senza carburante è una cellula a piedi.\n\nOrganizza i convogli sulla via principale (Hwy 1) e sulle piste parallele: carburante, farina, ricambi, generatori, a volte contanti. Rahman gli ha vietato di caricare pasta d’oppio. Hakimi gli ha vietato le casse di Viktor Sokolov, il contatto russo, quando il rischio di sequestro è alto.',
    personality: 'È calcolatore, cordiale, avido in modo visibile, con un sorriso da mercato. Non fa prediche. Samiullah Barakzai, il giudice, lo tollera. Faisal Noor, il propagandista radio, lo ignora. Hakimi lo tratta da fornitore. Rahman da dipendente che si crede socio.',
    appearanceItems: [
      'Gilet ricamato',
      'Anello d’oro',
      'Barba curata',
      'Non mostra il fucile',
      'Autisti afghani, targhe miste, teloni sporchi: convogli che vogliono sembrare traffico civile',
    ],
    networkSteps: [
      'Magazzino «Recinto Karwan» — Hwy 1 a est di Gereshk',
      'Tettoie, camion, cisterne, officina minima',
      'Convogli corti, tre o sei veicoli',
      'Radio civile a corto raggio, non la rete di propaganda di Faisal',
    ],
    networkNote: 'Sta al recinto come un padrone di ditta e ha casa nel bazar di Gereshk. I suoi uomini sanno cosa non devono caricare: pasta d’oppio e prodotto raffinato. I contenitori per Zahir, se ci sono, viaggiano come merce di magazzino. Le casse di Sokolov solo quando Hakimi lo permette.',
    relationshipItems: [
      'Abdul Rahman — tesoriere. Gli compra viveri e taniche. Pasta d’oppio e prodotto raffinato non salgono sui camion: i campi restano fuori dagli autisti.',
      'Zahir Popalzai — laboratorio a Lashkar Gah. Ha portato solvente e fatto troppe domande; ora i contenitori viaggiano come merce di magazzino, senza che gli autisti sappiano cosa c’è dentro.',
      'Omar Hakimi — capo dei combattenti. Gli compra il carburante che tiene in piedi le cellule.',
      'Rahmatullah Hotak — capo dei servizi informativi. Vende a Bashir indicazioni sui posti di blocco e compra i movimenti dei camion.',
      'Latif Ishaqzai — gestisce la pista in terra nel Dasht-e Margo. Riceve ricambi e carichi leggeri quando la Hwy 1 è troppo sorvegliata.',
      'Haji Khairullah Barech — valico di Zaranj, corrispondente non subordinato. Scambia carichi: taniche iraniane contro viveri, persone contro commissioni.',
      'Izatullah Noorzai — officina IED. A volte un passaggio per gli inneschi tra i ricambi, a pagamento e senza guardare dentro; Khatar evita i convogli di carburante quando può.',
    ],
    weakness: 'Minaccia logistica. Un colpo sul magazzino ferma il ritmo della rete. Un colpo su un solo camion ferma un viaggio. Senza di lui Hakimi resta a piedi e Rahman resta senza viveri sulle strade.',
    treeLinkSteps: [
      'Karwan-e-Dasht (logistica)',
      'Bashir Achakzai',
      'Convogli su Hwy 1 e piste',
      'Hakimi a piedi / Rahman senza viveri, se cade',
    ],
    treeLinkNote: 'Senza di lui gli altri rami restano chiusi nel proprio distretto. Alta importanza: la rete diventa lenta e locale.',
  },
  latifIshaqzai: {
    label: 'Pista',
    title: 'Latif Ishaqzai — "Pista"',
    meta: meta(metaIt, {
      name: 'Latif Ishaqzai',
      nickname: '"Pista"',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Distretto di Dishu, Dasht-e Margo',
      faction: 'Talebani — Karwan-e-Dasht',
      role: 'Gestore della pista d’atterraggio improvvisata',
      category: 'Logistica aerea improvvisata',
      association: 'Striscia in terra nel Dasht-e Margo — niente navaid, solo marche a vista',
    }),
    sections: sectionsIt,
    profile: 'Latif ha passato la vita a leggere il deserto: suolo, vento, sale. Non è un pilota e non è un trafficante di oppio. Dice dove si può atterrare e accende due fuochi come marche a vista.\n\nNella logistica Karwan-e-Dasht è il responsabile della pista in terra nel Dasht-e Margo, distretto di Dishu. I carichi sono leggeri: ricambi, denaro, persone, a volte un tecnico. Viktor Sokolov, il contatto russo, ha chiesto di usarla. Latif ha riferito a Bashir Achakzai, suo superiore, e Bashir non ha ancora detto di sì.',
    personality: 'È solitario, secco, poco interessato alla Shura-ye-Sangsar. Parla del vento come Nazar Mohammad Alizai (Tufan) parla del cielo, ma in orizzontale. Tiene lontano Abdul Rahman, tesoriere, perché l’oppio attira occhi nel deserto. Rispetta Haji Khairullah Barech, perché il valico è un mestiere simile: aprire e chiudere una porta.',
    appearanceItems: [
      'Kefiah chiara',
      'Viso bruciato dal vento',
      'Niente turbante',
      'Un veicolo con taniche, niente generatori fissi sulla striscia',
      'Niente edifici, niente luci permanenti',
    ],
    networkSteps: [
      'Pista in terra «Pista Latif» — Dasht-e Margo',
      'Striscia battuta, due fusti come soglia',
      'Tenda e veicolo lontano dal touchdown',
      'Fuochi solo se l’aereo sta arrivando: niente impianto, solo marche',
    ],
    networkNote: 'Niente radio lunga: una ricetrasmittente corta. Dopo l’uso copre i solchi. Se usata, la striscia si vede bene dall’aria. Se lasciata stare, il vento la copre. Non è una base: è una soglia che esiste solo quando lui la marca.',
    relationshipItems: [
      'Bashir Achakzai — responsabile dei convogli e superiore. La Hwy 1 muove il peso; la pista muove l’urgenza.',
      'Haji Khairullah Barech — valico di Zaranj, l’altro varco a ovest, quasi un rivale educato. Quando Zaranj è troppo calda Haji spinge carichi urgenti sulla pista; Latif resiste; Bashir decide.',
      'Omar Hakimi — capo dei combattenti. Ha fatto arrivare a Bashir la richiesta di Sokolov. Latif non vuole un aereo di armi sulla striscia.',
    ],
    weakness: 'Serve a rifornire e a far sparire persone. Per chi vola è poco pericolosa, a meno che sulla pista non arrivino MANPADS che non sono suoi. Media adesso; alta se Sokolov ottiene l’uso.',
    treeLinkSteps: [
      'Karwan-e-Dasht (logistica)',
      'Latif Ishaqzai',
      'Striscia nel Dasht-e Margo',
      'Unica porta aerea della rete',
    ],
    treeLinkNote: 'Senza Latif la striscia c’è ancora, ma nessuno la marca al momento giusto.',
  },
  hajiKhairullahBarech: {
    label: 'Haji',
    title: 'Haji Khairullah Barech',
    meta: meta(metaIt, {
      name: 'Khairullah Barech',
      nickname: '«Haji», al valico',
      age: 'Non confermata',
      nationality: 'Afghana — tribù Barech, Nimruz',
      origin: 'Zaranj e Helmand inferiore',
      faction: 'Talebani — Karwan-e-Dasht',
      role: 'Contrabbando di frontiera',
      category: 'Valico / dogana di fatto',
      association: 'Valico nord-est di Zaranj — persone, carburante iraniano, contante; non oppio, non armi',
    }),
    sections: sectionsIt,
    profile: 'Khairullah è un uomo di frontiera. Lo chiamano Haji al valico. I Barech, a Nimruz, tengono acqua, piste e parenti oltre il confine iraniano. Non è un talebano di Kandahar: è un talebano di Nimruz che accetta la bandiera della rete perché la bandiera gli lascia il fiume.\n\nNel Karwan-e-Dasht, il ramo logistico, controlla un recinto sul valico a nord-est di Zaranj e un guado stagionale. Fa passare persone, taniche di carburante iraniano, pezzi di ricambio civili, contante. Non fa passare le casse di Viktor Sokolov né i carichi raffinati di Zahir Popalzai. Abdul Rahman, tesoriere, ha tentato di comprargli i canali per l’oppio: ha detto di no.',
    personality: 'È impassibile, lento, offensivo con calma. Misura gli uomini dal debito. Non crede alle prediche di Faisal Noor, il propagandista radio, troppo lontane, e non teme Omar Hakimi, capo dei combattenti, troppo lontano. Teme i droni e le inondazioni. Non ospita Sokolov: un russo al valico è una fine.',
    appearanceItems: [
      'Turbante scuro voluminoso',
      'Scialle pesante',
      'Barba brizzolata',
      'Sguardo basso e fermo',
      'Si muove poco dal recinto; i figli fanno i corrieri sul guado e verso i magazzini',
    ],
    networkSteps: [
      'Recinto «Valico Haji» — nord-est di Zaranj, Nimruz',
      'Due magazzini bassi, bilancia, veicoli',
      'Guado stagionale verso il fiume, verso il lato iraniano',
      'Radio civile, niente torri, niente AAA',
    ],
    networkNote: 'Paga tutti i lati del confine, quanto basta per tenere aperta la porta. Tiene ostaggi per debiti, non prigionieri di guerra. Chiudere il recinto chiude la porta ovest della rete: Bashir dovrebbe scaricare tutto sulla Hwy 1.',
    relationshipItems: [
      'Bashir Achakzai — responsabile dei convogli, corrispondente, non capo. Taniche iraniane contro farina e ricambi; il valico riempie, la strada distribuisce.',
      'Abdul Rahman — tesoriere. Gli ha offerto l’oppio e si è sentito rispondere di no. Non è un no da nemico, è un no da doganiere: l’oppio chiude il valico.',
      'Latif Ishaqzai — l’altra porta, la striscia nel Dasht-e Margo. Haji spinge i carichi urgenti verso la pista quando Zaranj è calda; Latif resiste; Bashir decide.',
      'Samiullah Barakzai — giudice. Lo ha riconosciuto senza convocarlo al tribunale. Quel riconoscimento impedisce a Hakimi di «mettere ordine» sul fiume con i combattenti.',
    ],
    weakness: 'Minaccia di rifornimento, di passaggio persone e di movimento di contante. Poco pericoloso in combattimento, niente AAA. Se cade, Bashir sovraccarica la Hwy 1.',
    treeLinkSteps: [
      'Karwan-e-Dasht (logistica)',
      'Haji Khairullah Barech',
      'Valico di Zaranj',
      'Porta ovest della rete',
    ],
    treeLinkNote: 'Il rifiuto dell’oppio e delle armi non è ideologia. È il modo in cui tiene aperta la porta.',
  },
  abdulRahman: {
    label: 'Rahman',
    title: 'Abdul Rahman',
    meta: meta(metaIt, {
      name: 'Abdul Rahman',
      nickname: 'Non confermato',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Helmand, fascia di Gereshk / Lashkar Gah',
      faction: 'Talebani — Bayt al-Mal-e-Helmand',
      role: 'Tesoriere',
      category: 'Tesoreria / oppio',
      association: 'Campi in Helmand; laboratorio di Zahir; stipendi della rete',
    }),
    sections: sectionsIt,
    profile: 'Rahman comanda i campi, non le imboscate. Dirige il Bayt al-Mal-e-Helmand, la tesoreria della rete: ushr, pasta d’oppio, stipendi. Ha preso Zahir Popalzai perché sa pesare e tagliare. Non entra nel laboratorio: manda un cugino a ritirare il prodotto raffinato.\n\nPaga le famiglie perché Safi porti via i figli. Paga Hakimi, e Hakimi paga Khatar. A Bashir Achakzai compra viveri e taniche, e gli ha vietato pasta d’oppio e raffinato sui camion. Ha tentato di comprare i canali di Haji Khairullah Barech per l’oppio: ha detto di no.',
    personality: 'È avido in modo visibile, meno ideologo di Samiullah, più concreto di Faisal. Tratta Bashir da dipendente che si crede socio. Samiullah gli dà il riconoscimento religioso dell’ushr e tiene Zahir fuori dal tribunale, perché in pubblico la tesoreria deve restare accettabile. Rahman accetta quella distanza.',
    appearanceItems: [
      'Si fa vedere nei campi, non in laboratorio',
      'Non porta il mestiere in faccia: niente fiale, niente vetro',
      'Cugino come corriere verso Casa Shisha',
      'Ricevuto ogni tanto nel recinto di Samiullah, a sud-ovest di Kandahar',
    ],
    networkSteps: [
      'Campi di oppio — Helmand, intorno a Gereshk / nord di Lashkar Gah',
      'Laboratorio «Casa Shisha» — ritiro tramite cugino, Rahman non entra',
      'Soldi verso Hakimi, Faisal, Safi; viveri e taniche verso Bashir',
      'Valico di Zaranj chiuso all’oppio: Haji ha rifiutato',
    ],
    networkNote: 'I campi coltivano; Zahir trasforma. Sono due siti. Il prodotto raffinato non sale sui convogli di Bashir. I contenitori per il laboratorio, se servono, viaggiano come merce di magazzino.',
    relationshipItems: [
      'Samiullah Barakzai — giudice. Rahman gli porta l’ushr; Samiullah dà alla tesoreria la copertura religiosa e non riceve Zahir.',
      'Zahir Popalzai — chimico del laboratorio. Gli deve casa e soldi; Rahman gli deve il guadagno extra dei campi.',
      'Omar Hakimi — capo dei combattenti. Rahman paga gli stipendi; Hakimi tiene in piedi le cellule.',
      'Hamidullah Safi — reclutatore. Rahman paga le famiglie. Safi odia da dove arrivano i soldi, ma li prende.',
      'Bashir Achakzai — convogli. Autisti che non fanno domande; pasta e raffinato vietati sui camion.',
      'Haji Khairullah Barech — valico. No all’oppio: no da doganiere, non da nemico.',
    ],
    weakness: 'Minaccia indiretta, attraverso i soldi. Un colpo ai campi o al laboratorio non ferma i fucili il giorno dopo, ma ritarda stipendi e reclute. Senza Rahman la tesoreria si spezza in pasta grezza e debiti.',
    treeLinkSteps: [
      'Bayt al-Mal-e-Helmand (tesoreria)',
      'Abdul Rahman',
      'Campi + laboratorio Zahir',
      'Stipendi per Hakimi, Faisal, Safi',
    ],
    treeLinkNote: 'Senza di lui restano i campi, ma manca chi tiene insieme ushr, raffinazione e pagamenti.',
  },
  omarHakimi: {
    label: 'Hakimi',
    title: 'Omar Hakimi',
    meta: meta(metaIt, {
      name: 'Omar Hakimi',
      nickname: 'Non confermato',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Kandahar',
      faction: 'Talebani — Lashkar-e-Maiwand',
      role: 'Capo dei combattenti',
      category: 'Comando della lashkar',
      association: 'Cellule, AAA/MANPADS di Tufan, IED di Khatar — ordini di fuoco',
    }),
    sections: sectionsIt,
    profile: 'Hakimi comanda la Lashkar-e-Maiwand, il ramo armato. Dà gli ordini di fuoco. Samiullah gli copre le operazioni con le sentenze, non gli dice dove sparare. Quasi mai mette piede nell’ex tribunale: il palazzo non deve bruciarsi con lui.\n\nHa tolto Tufan dalle imboscate e gli ha dato AAA e MANPADS. Ha tolto a Khatar gli uomini dopo il veicolo sbagliato e gli ha lasciato il bancone. Compra da Bashir il carburante. Prende i ragazzi da Safi. I preavvisi di Hotak gli arrivano già puliti, spesso senza la fonte. Ha fatto arrivare a Bashir la richiesta di Sokolov sulla pista: le casse del russo, sui convogli, solo se il rischio di sequestro è basso.',
    personality: 'È il mestiere delle armi, non della predica. Tratta Bashir da fornitore. Non teme Haji, troppo lontano sul fiume, ma Samiullah gli ha riconosciuto il valico proprio perché Hakimi non «metta ordine» là con i combattenti. Rispetta chi gli rende le cellule meno visibili dall’alto.',
    appearanceItems: [
      'Compound con muro sud esposto — osservato da tetto',
      'Si muove con le cellule, non dal recinto del giudice',
      'Radio di comando, non la rete di propaganda di Faisal',
      'MANPADS e casse Sokolov passano da lui, non dal valico e non dalla pista (ancora)',
    ],
    networkSteps: [
      'Compound della lashkar — Kandahar',
      'Cresta Tufan — AAA / MANPADS, sud di Kandahar',
      'Officina Khatar — IED a ovest di Gereshk; lui marca la mappa, altri piantano',
      'Carburante da Recinto Karwan, Hwy 1 est di Gereshk',
    ],
    networkNote: 'Non sa esattamente dov’è Casa Shisha. Non gestisce Farid: Hotak gli passa solo l’avviso. Sokolov non lo presenta a Tufan: i missili arrivano come «roba dei fratelli».',
    relationshipItems: [
      'Samiullah Barakzai — giudice. Copertura delle operazioni, non ordini di fuoco. Hakimi al tribunale, quasi mai.',
      'Nazar Mohammad Alizai (Tufan) — contraerea. Senza di lui Hakimi muove uomini visibili dagli elicotteri.',
      'Izatullah Noorzai (Khatar) — IED. Gli ha tolto il comando di cellula; gli ha lasciato inneschi e mappe.',
      'Hamidullah Safi — reclute. I ragazzi finiscono alle cellule, non nei campi di Rahman.',
      'Bashir Achakzai — carburante. Cellula senza taniche = cellula a piedi. Casse Sokolov vietate se il sequestro è alto.',
      'Rahmatullah Hotak — preavvisi già puliti. Hakimi spesso non sa da dove arrivano.',
      'Viktor Sokolov — contatto russo. Hakimi è il taglio: armi sì, viso del russo no, pista non ancora.',
    ],
    weakness: 'Minaccia di fuoco diretta. Se cade, Tufan e Khatar restano mestieri senza chi decide dove colpire. Senza carburante di Bashir e stipendi di Rahman, la lashkar si ferma comunque.',
    treeLinkSteps: [
      'Lashkar-e-Maiwand (combattenti)',
      'Omar Hakimi',
      'Ordini di fuoco',
      'Tufan / Khatar / cellule',
    ],
    treeLinkNote: 'Non è il consiglio. È chi rende la rete capace di sparare. Senza di lui restano sentenze, soldi e radio, e poche imboscate coordinate.',
  },
  faisalNoor: {
    label: 'Faisal',
    title: 'Faisal Noor',
    meta: meta(metaIt, {
      name: 'Faisal Noor',
      nickname: 'Non confermato',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Kandahar',
      faction: 'Talebani — Sada-ye-Maiwand',
      role: 'Propagandista radio',
      category: 'Propaganda',
      association: 'Rete radio e torri; sentenze del cortile lette in antenna',
    }),
    sections: sectionsIt,
    profile: 'Faisal è la voce, non il cortile. Dirige la propaganda nel ramo Sada-ye-Maiwand. Hamidullah Safi è compagno di ramo, non un subordinato: la radio prepara i villaggi, il cortile raccoglie chi si alza. Safi ha rifiutato di diventare la seconda voce, perché la radio lo brucerebbe.\n\nPrende le sentenze affisse nel cortile di Samiullah e le legge in antenna. Non entra nell’ex tribunale: la voce è già riconoscibile, e il palazzo non deve bruciarsi con lui. Hotak non sopporta il rumore. Tufan invidia una voce che arriva lontano senza farsi sparare.',
    personality: 'È teatrale, volgare per il giudice, troppo lontano per Haji. Ignora Bashir. Crede alle prediche più di Rahman. Non è un capo combattenti e non tiene una cellula.',
    appearanceItems: [
      'Microfono, non fucile in primo piano',
      'Torri radio, non l’antenna civile sul tetto del tribunale',
      'Voce riconoscibile in etere',
      'Non si fa vedere nel recinto di Samiullah',
    ],
    networkSteps: [
      'Torri / rete radio Sada-ye-Maiwand — Kandahar e dintorni',
      'Sentenze dal cortile dell’ex tribunale, lette in antenna',
      'Villaggi preparati; reclute raccolte da Safi a Khakrez',
      'Niente ponte verso il ripetitore di Hotak né verso la radio civile di Bashir',
    ],
    networkNote: 'L’antenna sul palazzo del giudice è un resto civile, corto raggio, non la sua rete. Senza Safi parla a una rete che non si rinnova. Senza Tufan, le torri restano più esposte a chi vola basso.',
    relationshipItems: [
      'Samiullah Barakzai — giudice. Faisal legge le sentenze; Samiullah lo trova volgare e lo tiene fuori dal recinto.',
      'Hamidullah Safi — stesso ramo. Radio e cortile. Faisal non è il suo capo.',
      'Rahmatullah Hotak — servizi informativi. Non sopporta chi fa rumore, Faisal per primo.',
      'Nazar Mohammad Alizai (Tufan) — invidia la voce. Le torri stanno sotto il suo cielo.',
      'Omar Hakimi — prende uomini che la radio ha scaldato e Safi ha consegnato.',
      'Haji Khairullah Barech — non crede alle prediche, troppo lontane dal fiume.',
    ],
    weakness: 'Minaccia di influenza, non di fuoco. Se le torri cadono, i villaggi smettono di arrivare già convinti. Se Safi cade, la voce resta e il flusso di reclute no.',
    treeLinkSteps: [
      'Sada-ye-Maiwand (propaganda / reclutamento)',
      'Faisal Noor',
      'Torri radio',
      'Villaggi preparati per Safi e Hakimi',
    ],
    treeLinkNote: 'Senza di lui Safi parla solo nel cortile e le sentenze di Samiullah restano sul muro.',
  },
  viktorSokolov: {
    label: 'Sokolov',
    title: 'Viktor Sokolov',
    meta: meta(metaIt, {
      name: 'Viktor Sokolov',
      nickname: 'Non confermato',
      age: 'Non confermata',
      nationality: 'Russa',
      origin: 'Non confermata',
      faction: 'Contatto armi — fuori dalla rete talebana',
      role: 'Fornitore di armi',
      category: 'Rifornimento esterno / MANPADS',
      association: 'Taglio: Omar Hakimi. Vietato al tribunale, al valico, e sulla pista finché Bashir non dice sì',
    }),
    sections: sectionsIt,
    profile: 'Sokolov non è un talebano. È il contatto russo sulle armi. I MANPADS di Tufan passano da Hakimi e arrivano come «roba dei fratelli»: Tufan non lo ha mai incontrato. Khatar non vuole inneschi dalla sua rete.\n\nHa chiesto la pista in terra di Latif Ishaqzai nel Dasht-e Margo. Hakimi ha portato la richiesta a Bashir. Bashir non ha ancora detto di sì. Latif non vuole un aereo di armi sulla striscia. Samiullah ha vietato che metta piede nell’ex tribunale. Haji non lo ospita al valico: un russo là è una fine.',
    personality: 'Resta fuori dal recinto, fuori dal fiume, fuori dalla cresta. Il mestiere è il taglio: Hakimi vede le casse, gli altri vedono «i fratelli». Non predica, non paga ushr, non comanda cellule.',
    appearanceItems: [
      'Non osservato al tribunale, al valico, sulla Cresta Tufan',
      'Nessuna firma fissa in Helmand o Kandahar in questo file',
      'Casse destinate a Hakimi, non a Bashir se il sequestro è alto',
      'Richiesta aperta sulla pista Latif — non autorizzata',
    ],
    networkSteps: [
      'Ingresso: Hakimi, Lashkar-e-Maiwand',
      'Uscita verso Tufan: MANPADS, provenienza coperta',
      'Convogli Bashir: casse solo se Hakimi lo permette e il rischio è basso',
      'Pista Dasht-e Margo e valico Zaranj: ancora no',
    ],
    networkNote: 'Se ottiene la pista, la striscia diventa porta d’armi e la minaccia per chi vola sale. Finché Bashir dice no, Sokolov resta un tubo verso Hakimi, non una base.',
    relationshipItems: [
      'Omar Hakimi — unico taglio utile in questo file. Armi sì, faccia no.',
      'Nazar Mohammad Alizai (Tufan) — riceve i MANPADS senza sapere il russo.',
      'Izatullah Noorzai (Khatar) — rifiuta inneschi «dei fratelli».',
      'Bashir Achakzai / Latif Ishaqzai — convogli e pista: sequestro e marche a vista. Ancora chiusi o condizionati.',
      'Samiullah Barakzai — vietato nel palazzo dove si giudica.',
      'Haji Khairullah Barech — vietato al valico.',
    ],
    weakness: 'Minaccia di rifornimento, soprattutto MANPADS. Lui, da solo, non tiene una cresta. Tagliare Hakimi taglia Sokolov. Aprire la pista alza il valore del file.',
    treeLinkSteps: [
      'Sokolov (esterno)',
      'Omar Hakimi',
      'Casse / MANPADS',
      'Tufan, non il valico, non la pista (ancora)',
    ],
    treeLinkNote: 'Fuori dalla Shura. Dentro il cielo, se i missili arrivano. Senza Hakimi non ha destinatario talebano utile.',
  },
  faridAhmadKhan: {
    label: 'Farid',
    title: 'Farid Ahmad Khan',
    meta: meta(metaIt, {
      name: 'Farid Ahmad Khan',
      nickname: 'Non confermato',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Kandahar — visto in distretto mercato',
      faction: 'Fonte pagata — non affiliato alla rete',
      role: 'Fonte di Rahmatullah Hotak',
      category: 'HUMINT',
      association: 'Solo Hotak; intermediario venditore di telefoni usati; mai la stessa stanza',
    }),
    sections: sectionsIt,
    profile: 'Farid non è un talebano. È una fonte pagata. L’unico contatto nella rete è Rahmatullah Hotak, Daftar-e-Khabar. Non si trovano mai nella stessa stanza: un venditore di telefoni usati in città passa messaggi e pagamenti.\n\nVende movimenti, orari, posti di blocco. Hotak pulisce il materiale e lo manda a Hakimi come preavviso e a Bashir come indicazioni di percorso, spesso senza dire da dove arriva. Hotak lo paga, lo tiene con una fotografia di sorveglianza — Farid ripreso dove non dovrebbe — e non lo stima.',
    personality: 'Il rapporto è sporco da entrambi i lati. Farid non entra nel tribunale, non parla in radio, non pianta IED. Quando risulta in servizio, il ripetitore di Cresta Karg resta spento: Hotak non emette mentre la fonte è esposta.',
    appearanceItems: [
      'Maschio, distretto mercato, almeno un passaggio alle 06:14 locali',
      'Nessun turbante da comandante, nessun fucile in questo file',
      'Non osservato sulla Cresta Karg né nel recinto di Samiullah',
      'Contatto solo tramite intermediario',
    ],
    networkSteps: [
      'Venditore di telefoni usati — città, taglio tra Farid e Hotak',
      'Pagamenti e messaggi, mai incontro diretto',
      'Hotak, Cresta Karg / casa sicura a valle, Arghandab',
      'Uscita: preavvisi a Hakimi, percorsi a Bashir',
    ],
    networkNote: 'Senza Hotak la fonte non ha un destinatario utile nella rete. Senza Farid, Hotak perde il pezzo più sporco e più utile. Hakimi non deve sapere il nome.',
    relationshipItems: [
      'Rahmatullah Hotak — unico handler talebano. Paga, ricatta, non stima.',
      'Omar Hakimi — riceve avvisi già puliti, spesso senza la fonte.',
      'Bashir Achakzai — riceve indicazioni sui posti di blocco, in cambio movimenti dei camion verso Hotak.',
      'Samiullah Barakzai — vede solo quello che Hotak seleziona. Non gestisce Farid.',
    ],
    weakness: 'Minaccia di informazioni, non di fuoco. Bruciare Farid acceca i preavvisi. Bruciare Hotak lascia Farid senza a chi vendere. La foto di ricatto è anche una firma: se esce, la fonte muore come asset.',
    treeLinkSteps: [
      'Farid Ahmad Khan (fonte pagata)',
      'Intermediario (telefoni usati)',
      'Rahmatullah Hotak',
      'Preavvisi a Hakimi e Bashir',
    ],
    treeLinkNote: 'Non è un ramo della rete. È un tubo. Se il tubo si rompe, la lashkar resta armata e cieca.',
  },
  afghanistanChart: {
    label: 'Afghanistan',
    title: 'Carta operativa — Afghanistan',
    body: 'Mappa operativa del teatro. Nessun filo sulla carta: riferimento geografico per Kandahar, Helmand, Hwy 1, Dasht-e Margo e Zaranj.',
  },
};

export const lidcWhiteboardItemsEn = {
  samiullahBarakzai: {
    label: 'Sangsar',
    title: 'Maulvi Samiullah Barakzai — "Sangsar"',
    meta: meta(metaEn, {
      name: 'Samiullah Barakzai',
      nickname: '"Sangsar" — The Rock',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Panjwai District, Kandahar',
      faction: 'Taliban — Shura-ye-Sangsar',
      role: 'Judge and political-religious coordinator',
      category: 'Political-religious direction',
      association: 'Occupied former district courthouse, Kandahar',
    }),
    sections: sectionsEn,
    profile: 'Samiullah comes from a family of mullahs in Panjwai, not a family of commanders. He studied in a Kandahar madrasa and spent years writing rulings on land, debt and feuds without ever leading an ambush. The other network chiefs accept him in the chair for that reason: he does not ask for command of the fighters.\n\nHe chairs the Shura-ye-Sangsar, the political-religious council that holds together the five branches of the local Taliban network: the council itself, Abdul Rahman’s treasury, Omar Hakimi’s fighters, propaganda and recruitment (Faisal Noor and Hamidullah Safi), and Bashir Achakzai’s logistics. Anyone who ignores the council, on paper at least, loses Rahman’s money and Safi’s recruits. He does not issue fire orders to Hakimi. His work is to keep those five branches as one organisation.',
    personality: 'He is slow, formal and vain in a clerical way. He speaks little, corrects others and does not raise his voice. Foreigners are not a target to hit: they are a problem to keep out of the compound where he judges. Viktor Sokolov, the Russian arms contact, is not to set foot there. He fears a wrong ruling more than an airstrike, because a wrong ruling costs him the village elders.',
    appearanceItems: [
      'Almost never leaves the compound of the former district courthouse, the occupied government building in south-west Kandahar from which he chairs the council',
      'Does not carry long weapons',
      'Two or three armed men at the compound gate, not a garrison',
      'Does not use a satellite phone',
      'Handwritten rulings posted in the inner courtyard of the building',
    ],
    networkSteps: [
      'Occupied former district courthouse — south-west Kandahar city',
      'Compound wall, courtyard, hearing room',
      'Civilian rooftop aerial (left over from the building, not a military repeater)',
      'Runners on foot; intelligence reports through Rahmatullah Hotak',
    ],
    networkNote: 'The aerial on the roof is the building’s old television/radio antenna. It is only good for short calls within the city: it is not linked to Faisal Noor’s propaganda radio net. Rahman, the treasurer, is received in the compound now and then. Hakimi, the fighting chief, almost never. Faisal Noor does not enter the building: his voice is already recognisable on the air, and the courthouse must not burn with him.',
    relationshipItems: [
      'Rahmatullah Hotak — intelligence chief (Daftar-e-Khabar). Gathers information for him. In return he gets the council’s protection.',
      'Abdul Rahman — brings ushr money, the religious tithe on harvests. Samiullah gives the treasury religious recognition.',
      'Omar Hakimi — commands the fighters. The judge covers operations with rulings; he does not give fire orders.',
      'Faisal Noor — radio propagandist. Takes the rulings posted in the courtyard and reads them on air. Samiullah finds him vulgar, but radio travels farther than a wall.',
      'Hamidullah Safi — recruiter. Samiullah blesses him in public: the boys reach the cells with the council’s recognition.',
    ],
    weakness: 'He does not plan ambushes. If he stays in place the five branches stay a network. If he is gone, treasury, fighters, propaganda and logistics go back to working each for themselves.',
    treeLinkSteps: [
      'Shura-ye-Sangsar',
      'Samiullah Barakzai',
      'Religious cover',
      'Five branches held together',
    ],
    treeLinkNote: 'Without Samiullah the five branches remain five trades standing side by side. He is not a military commander, but he holds the organisation together politically.',
  },
  rahmatullahHotak: {
    label: 'Karg',
    title: 'Rahmatullah Hotak — "Karg"',
    meta: meta(metaEn, {
      name: 'Rahmatullah Hotak',
      nickname: '"Karg" — The Crow',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Arghandab District, Kandahar',
      faction: 'Taliban — Shura-ye-Sangsar / Daftar-e-Khabar',
      role: 'Intelligence chief',
      category: 'Intelligence',
      association: 'Sole Taliban contact for the source Farid Ahmad Khan',
    }),
    sections: sectionsEn,
    profile: 'Hotak grew up in Arghandab as a courier and then an informant. He has never led an armed cell. Shepherds call him Karg because they see him on the ridges above the valley and then he is gone.\n\nHe runs the Daftar-e-Khabar, the intelligence office of the Shura-ye-Sangsar, Samiullah Barakzai’s council. He is the only Taliban authorised to handle Farid Ahmad Khan, a paid source: not as a friend, as merchandise. What Farid sells — movements, timings, checkpoints — becomes early warning for Omar Hakimi, the fighting chief, and route advice for Bashir Achakzai, who moves the convoys.',
    personality: 'He is taciturn, suspicious, almost superstitious. He counts things. He does not raise his voice and does not make speeches. He cannot stand noise, Faisal Noor first of all, the radio propagandist. The relationship with Farid is dirty: he pays him, blackmails him, does not respect him.',
    appearanceItems: [
      'Wool pakol cap, not a turban',
      'Binoculars, notebook, a small low-power radio repeater',
      'Avoids the main road that cuts through Arghandab',
      'The repeater stays off during the same hours Farid appears to be on duty',
    ],
    networkSteps: [
      'Observation post “Crest Karg” — hills north-west of Arghandab',
      'Stone shelter, tarp, low repeater (short signal, not Faisal’s net)',
      'In the city: a used-phone seller acts as go-between',
      'Sleeps in the valley, in a safe house, not on the ridge',
    ],
    networkNote: 'Hotak and Farid are never in the same room. The phone seller passes messages and payments. The ridge repeater is only to listen and to push a short-range warning: it is not a bridge into the propaganda radio. The match between a dead repeater and Farid’s hours suggests Hotak will not transmit while the source is exposed.',
    relationshipItems: [
      'Samiullah Barakzai — his only superior, judge and council chair. Hotak brings him selected news, not the raw take.',
      'Farid Ahmad Khan — most useful and dirtiest source. A surveillance photograph, Farid caught where he should not be, used as leverage.',
      'Omar Hakimi — fighting chief. Receives cleaned warnings, often without knowing where they come from.',
      'Bashir Achakzai — convoy lead. Buys checkpoint advice; in return he passes truck movements.',
      'Nazar Mohammad Alizai (Tufan) — AAA / MANPADS battery south of Kandahar. Hotak does not share observers with him: a ridge that shoots and a paid source must not coincide.',
    ],
    weakness: 'An information threat, not a fire threat. Without him the fighters stay armed, but Hakimi loses early warning and Bashir loses roads already read. The council goes blind.',
    treeLinkSteps: [
      'Farid Ahmad Khan (paid source)',
      'Rahmatullah Hotak',
      'Shura-ye-Sangsar',
      'Warnings to Hakimi and Bashir',
    ],
    treeLinkNote: 'He is the bridge between Farid Khan and the Taliban. Without him the source has no useful recipient, and the council loses its information.',
  },
  hamidullahSafi: {
    label: 'Ustad',
    title: 'Hamidullah Safi — "Ustad"',
    meta: meta(metaEn, {
      name: 'Hamidullah Safi',
      nickname: '“Ustad”, among the boys',
      age: '29',
      nationality: 'Afghan',
      origin: 'Khakrez District, Kandahar',
      faction: 'Taliban — Sada-ye-Maiwand',
      role: 'Recruiter',
      category: 'Recruitment',
      association: 'Village madrasa in Khakrez — recruiting, not training',
    }),
    sections: sectionsEn,
    profile: 'Safi is twenty-nine. The boys call him Ustad, “teacher”, because he talks like a courtyard instructor, not like a commander. Son of a village imam in Khakrez, he learned to persuade boys before he learned to shoot. He is not a propagandist: he does not sit at the microphone. He is not a fighting chief: he does not keep a cell. He walks the boys to the lashkar gate and then leaves them to others.\n\nHe finds, persuades, moves. He works with family debt, revenge, hunger and pride. Abdul Rahman, the treasurer, pays the families to let the sons go. He refused to become Faisal Noor’s second voice — Faisal is the radio propagandist — because radio would burn him.',
    personality: 'He is charismatic in a young way, not theatrical like Faisal. He believes what he says more than Rahman and less than Samiullah Barakzai, the judge. He bristles if he is called a soldier. He fears Rahmatullah Hotak, the intelligence chief: a list of names in those hands is a death sentence.',
    appearanceItems: [
      'Young, black beard',
      'Black waistcoat over a white kameez (long tunic)',
      'No turban',
      'No long weapons at the madrasa',
      'White van with a repaired bumper: he moves the boys in it when the village is quiet',
    ],
    networkSteps: [
      'Madrasa “Safi’s Courtyard” — north of Kandahar, Khakrez district',
      'One-storey building, tree, compound wall: lessons in the courtyard, not a firing range',
      'Departures at night or at dawn, when the village is not watching',
      'Weapons only later, from Omar Hakimi’s cells',
    ],
    networkNote: 'It is not a training camp: here they talk and they leave. He avoids Gereshk and Helmand, the treasury’s ground, because there the boys end up in Rahman’s opium fields instead of Hakimi’s cells.',
    relationshipItems: [
      'Faisal Noor — same branch, Sada-ye-Maiwand (propaganda and recruitment), not his boss. Faisal’s radio prepares the villages; Safi’s courtyard collects whoever stands up.',
      'Omar Hakimi — fighting chief. Where the boys end up. In return Safi keeps them off the opium hoes.',
      'Abdul Rahman — treasurer. Pays the families. Safi hates that the money comes from opium, but he takes it.',
      'Samiullah Barakzai — judge and council chair. Blesses him in public and finds him too heated in private.',
    ],
    weakness: 'A threat of new men, not of fire. If the madrasa closes, the flow of recruits toward Hakimi stops. Faisal is left talking to a network that does not renew itself.',
    treeLinkSteps: [
      'Sada-ye-Maiwand (propaganda / recruitment)',
      'Hamidullah Safi',
      'Khakrez madrasa',
      'Recruits toward Hakimi',
    ],
    treeLinkNote: 'Without Safi, Hakimi burns through villages and Faisal talks to a network that does not renew itself.',
  },
  zahirPopalzai: {
    label: 'Shisha',
    title: 'Zahir Popalzai — "Shisha"',
    meta: meta(metaEn, {
      name: 'Zahir Popalzai',
      nickname: '"Shisha"',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'North of Lashkar Gah, Helmand',
      faction: 'Taliban — Bayt al-Mal-e-Helmand',
      role: 'Clandestine laboratory supervisor',
      category: 'Treasury / processing',
      association: 'Laboratory north of Lashkar Gah — processing, not cultivation',
    }),
    sections: sectionsEn,
    profile: 'Zahir is not an opium lord. He is a former chemistry teacher from Lashkar Gah. Abdul Rahman, the treasurer, took him because he can weigh and cut, not because he can shoot. The nickname Shisha comes from the laboratory glass, like the tubes of a water pipe.\n\nHe is the only person responsible for processing in the treasury, the Bayt al-Mal-e-Helmand branch. Raw opium paste arrives from the fields; Zahir works it and returns a refined product that is worth more. He does not command the fields and does not take loads to the border.',
    personality: 'He is anxious and educated. He is not an ideologue. He fears Rahman more than the coalition. He smokes constantly, yellow fingers. Samiullah Barakzai, the judge, considers him impure because of the opium: both Rahman and the council want that distance. The laboratory has to stay invisible so that, in public, the treasury stays acceptable.',
    appearanceItems: [
      'Prayer cap, no turban',
      'Nicotine-yellow fingers',
      'Rarely leaves the house-laboratory compound',
      'School notebooks for the weights and doses',
    ],
    networkSteps: [
      'Laboratory “House Shisha” — north of Lashkar Gah, Helmand',
      'Walled house between opium fields and a canal',
      'Plastic sheeting, drums, generator, drain pit: processing, not an arms store',
      'Two helpers, unarmed',
    ],
    networkNote: 'Rahman does not enter: he sends a cousin to collect the product. Omar Hakimi, the fighting chief, does not know exactly where it is. The fields grow; the laboratory processes. They are two different sites, and they have to stay that way.',
    relationshipItems: [
      'Abdul Rahman — treasurer and master. Zahir owes him a house and money; Rahman owes him the extra profit the fields cannot make alone.',
      'Bashir Achakzai — convoy lead. Brought solvent and asked too many questions. Containers now arrive as warehouse goods, without the drivers knowing what is inside.',
      'Samiullah Barakzai — judge. Will not receive him at the courthouse. In public the treasury stays acceptable only because the laboratory stays out of the council’s sight.',
    ],
    weakness: 'An indirect threat, through money. A strike on the laboratory does not stop the rifles the next day, but it cuts Rahman’s profit and delays wages for Hakimi, Faisal Noor and Hamidullah Safi.',
    treeLinkSteps: [
      'Rahman’s opium fields',
      'Zahir Popalzai',
      'Laboratory at Lashkar Gah',
      'Money for Hakimi, Faisal, Safi',
    ],
    treeLinkNote: 'Without him the treasury sells raw opium paste: less profit, more people in the middle, slower wages.',
  },
  nazarMohammadAlizai: {
    label: 'Tufan',
    title: 'Nazar Mohammad Alizai — "Tufan"',
    meta: meta(metaEn, {
      name: 'Nazar Mohammad Alizai',
      nickname: '"Tufan" — Storm',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Dand District, Kandahar',
      faction: 'Taliban — Lashkar-e-Maiwand',
      role: 'Air-defence lead',
      category: 'Tactical air defence',
      association: 'AAA / MANPADS battery — ridge south of Kandahar',
    }),
    sections: sectionsEn,
    profile: 'Alizai spent years as a gunner on open vehicles. A helicopter killed his brother; since then the sky has been his work. Omar Hakimi, the fighting chief, pulled him off ambushes because on the ground he wasted ammunition and against aircraft he used it well.\n\nHe is the only referent in Lashkar-e-Maiwand, the armed branch, for the low-level air threat. He keeps towed AAA, heavy machine guns and a few MANPADS. The missiles come through Hakimi; Tufan does not know for certain that Viktor Sokolov, the Russian arms contact, sits behind them.',
    personality: 'He is stubborn, bitter and simple. He treats the sky as a personal enemy. He respects Hakimi because Hakimi gave him the missiles. He envies Faisal Noor, the radio propagandist, whose voice travels far without being shot at. He chews naswar, dipping tobacco. He prays looking up.',
    appearanceItems: [
      'No turban',
      'Camouflage jacket over the kameez (long tunic)',
      'Narrow gaze, often against the light, hunting aircraft',
      'Moves the AAA pieces in a short radius around the ridge, so he is not a fixed target',
    ],
    networkSteps: [
      'Battery “Crest Tufan” — south of Kandahar',
      'Towed AAA, sandbags, tarps',
      'Vehicle with a heavy machine gun',
      'MANPADS hides and dummy pieces (decoys)',
    ],
    networkNote: 'He uses his own observers below Crest Tufan, not Rahmatullah Hotak’s net (Crest Karg, Arghandab). Different ground; they still avoid each other: Hotak does not want the battery tied to the source, Tufan does not want intelligence men around the MANPADS. He sleeps in a mid-slope quarry, not on the gun line.',
    relationshipItems: [
      'Omar Hakimi — fighting chief. Gave him this trade and the MANPADS. Without Tufan, Hakimi moves men visible to helicopters.',
      'Viktor Sokolov — Russian contact. Tufan has never met him. The MANPADS arrive as “the brothers’ stuff”, with no explanation of origin.',
      'Bashir Achakzai — convoy lead. His trucks raise dust and ruin the view of the sky. A trade conflict, not a council feud.',
    ],
    weakness: 'A direct air threat: AAA and MANPADS. No political weight. Without the battery, Samiullah’s former courthouse, Faisal’s radio towers and the network’s safe houses sit more exposed to whoever flies low.',
    treeLinkSteps: [
      'Lashkar-e-Maiwand (fighters)',
      'Nazar Mohammad Alizai',
      'Crest Tufan',
      'Flying low over Kandahar costs more',
    ],
    treeLinkNote: 'His work makes it expensive to fly low over Kandahar, Faisal’s radio towers and Samiullah’s occupied courthouse.',
  },
  izatullahNoorzai: {
    label: 'Khatar',
    title: 'Izatullah Noorzai — "Khatar"',
    meta: meta(metaEn, {
      name: 'Izatullah Noorzai',
      nickname: '"Khatar" — Danger',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Gereshk District, Helmand',
      faction: 'Taliban — Lashkar-e-Maiwand',
      role: 'Mines and IED lead',
      category: 'Mine warfare',
      association: 'IED workshop west of Gereshk',
    }),
    sections: sectionsEn,
    profile: 'Noorzai is a roadside mechanic. The nickname Khatar, “danger”, stuck after a mine took two fingers off his left hand: he learned to build them by being under one. Omar Hakimi, the fighting chief, forbade him from commanding a cell after his group blew up the wrong vehicle.\n\nIn Lashkar-e-Maiwand, the armed branch, he produces charges, initiators, homemade anti-tank mines and traps. He does not decide where to strike. He gets a mark on a map from one of Hakimi’s men and prepares the device. Fighters put it in the ground. He builds it.',
    personality: 'He is irritable, superstitious and rude. He resents Hakimi for taking his men, but he still obeys. He cannot stand Zahir Popalzai, the chemist at the opium laboratory: the smell of that house reminds him of the wrong fumes. He does not want initiators from Viktor Sokolov’s network, the Russian contact.',
    appearanceItems: [
      'Mutilated left hand (two fingers gone)',
      'No turban',
      'Burn scar on the neck',
      'Generator audible when running, in the workshop',
    ],
    networkSteps: [
      'Workshop “Farm Khatar” — west of Gereshk, Helmand',
      'Shed: batteries, cable, fertiliser, generator',
      'Moved on a cargo tricycle, short loads',
      'Notes, not radio: no electromagnetic signature',
    ],
    networkNote: 'He avoids Bashir Achakzai’s fuel convoys when he can: a seizure on Hwy 1 must not lead to the initiators. A crate, paid, may still ride among spare parts. Material does not stay long in the shed: it goes out to Hakimi’s cells.',
    relationshipItems: [
      'Omar Hakimi — fighting chief and superior. Took his men and left him the bench, the maps and people who plant devices.',
      'Bashir Achakzai — convoy lead. For a fee hides a crate among spare parts, and can refuse when the seizure risk is high.',
      'Abdul Rahman — treasurer. Pays Hakimi, Hakimi pays Khatar. Izatullah does not want opium near the fertiliser.',
    ],
    weakness: 'Dangerous to anyone moving on the ground and to helicopters at low level on the same tracks. The workshop, on its own, is a soft target from the air. Hakimi can replace him, but not quickly.',
    treeLinkSteps: [
      'Lashkar-e-Maiwand (fighters)',
      'Izatullah Noorzai',
      'IED workshop at Gereshk',
      'Tracks made dangerous without an ambush',
    ],
    treeLinkNote: 'Important on the ground, irrelevant in politics. If he is gone, the lashkar loses the man who makes roads dangerous even where there is no ambush.',
  },
  bashirAchakzai: {
    label: 'Karwan',
    title: 'Bashir Achakzai — "Karwan"',
    meta: meta(metaEn, {
      name: 'Bashir Achakzai',
      nickname: '"Karwan" — The Caravan',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Achakzai belt of Spin Boldak, Kandahar',
      faction: 'Taliban — Karwan-e-Dasht',
      role: 'Convoy lead',
      category: 'Logistics',
      association: 'Convoys on Hwy 1 and tracks — fuel, food, spares; not opium, not Sokolov’s crates',
    }),
    sections: sectionsEn,
    profile: 'Bashir is a merchant before he is a Taliban. The Achakzai, from the Spin Boldak belt, hold the roads. He holds the trucks. He runs Karwan-e-Dasht, the logistics branch of the network. Abdul Rahman, the treasurer, took him because his drivers do not ask questions. Omar Hakimi, the fighting chief, uses him because a cell without fuel is a cell on foot.\n\nHe organises convoys on the main highway (Hwy 1) and the parallel tracks: fuel, flour, spares, generators, sometimes cash. Rahman forbade him from loading opium paste. Hakimi forbade Viktor Sokolov’s crates — the Russian contact — when the seizure risk is high.',
    personality: 'He is calculating, cordial, visibly greedy, with a market smile. He does not preach. Samiullah Barakzai, the judge, tolerates him. Faisal Noor, the radio propagandist, ignores him. Hakimi treats him as a supplier. Rahman treats him as an employee who thinks he is a partner.',
    appearanceItems: [
      'Embroidered waistcoat',
      'Gold ring',
      'Trimmed beard',
      'Does not show a rifle',
      'Afghan drivers, mixed plates, dirty tarps: convoys meant to look like civilian traffic',
    ],
    networkSteps: [
      'Warehouse “Karwan Compound” — Hwy 1 east of Gereshk',
      'Sheds, trucks, tanks, a minimal workshop',
      'Short convoys, three to six vehicles',
      'Short-range civilian radio, not Faisal’s propaganda net',
    ],
    networkNote: 'He stands in the compound like a firm owner and keeps a house in the Gereshk bazaar. His men know what they must not load: opium paste and refined product. Zahir’s containers, when they move, travel as warehouse goods. Sokolov’s crates only when Hakimi allows it.',
    relationshipItems: [
      'Abdul Rahman — treasurer. Buys food and jerrycans. Opium paste and refined product do not go on the trucks: the fields stay off the drivers.',
      'Zahir Popalzai — laboratory at Lashkar Gah. Brought solvent and asked too many questions; containers now travel as warehouse goods, without the drivers knowing what is inside.',
      'Omar Hakimi — fighting chief. Buys the fuel that keeps the cells moving.',
      'Rahmatullah Hotak — intelligence chief. Sells Bashir checkpoint advice and buys truck movements.',
      'Latif Ishaqzai — runs the dirt strip in the Dasht-e Margo. Gets spares and light loads when Hwy 1 is too watched.',
      'Haji Khairullah Barech — Zaranj crossing, counterpart not subordinate. Swaps loads: Iranian fuel for food, people for commissions.',
      'Izatullah Noorzai — IED workshop. Sometimes a ride for initiators among spare parts, paid and uninspected; Khatar avoids the fuel convoys when he can.',
    ],
    weakness: 'A logistics threat. A strike on the warehouse stops the network’s rhythm. A strike on one truck stops one trip. Without him Hakimi is on foot and Rahman has no food on the roads.',
    treeLinkSteps: [
      'Karwan-e-Dasht (logistics)',
      'Bashir Achakzai',
      'Convoys on Hwy 1 and tracks',
      'Hakimi on foot / Rahman without food, if he falls',
    ],
    treeLinkNote: 'Without him the other branches stay locked in their own districts. High importance: the network becomes slow and local.',
  },
  latifIshaqzai: {
    label: 'Pista',
    title: 'Latif Ishaqzai — "Pista"',
    meta: meta(metaEn, {
      name: 'Latif Ishaqzai',
      nickname: '"Pista"',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Dishu District, Dasht-e Margo',
      faction: 'Taliban — Karwan-e-Dasht',
      role: 'Improvised airstrip manager',
      category: 'Improvised air logistics',
      association: 'Dirt strip in the Dasht-e Margo — no navaids, visual marks only',
    }),
    sections: sectionsEn,
    profile: 'Latif has spent his life reading the desert: soil, wind, salt. He is not a pilot and not an opium trafficker. He says where a landing is possible and lights two fires as visual marks.\n\nIn Karwan-e-Dasht logistics he runs the dirt strip in the Dasht-e Margo, Dishu district. Loads are light: spares, cash, people, sometimes a technician. Viktor Sokolov, the Russian contact, has asked to use it. Latif reported that to Bashir Achakzai, his superior, and Bashir has not said yes yet.',
    personality: 'He is solitary, dry, little interested in the Shura-ye-Sangsar. He talks about wind the way Nazar Mohammad Alizai (Tufan) talks about the sky, but horizontally. He keeps Abdul Rahman, the treasurer, away, because opium draws eyes into the desert. He respects Haji Khairullah Barech, because the crossing is a similar trade: opening and closing a door.',
    appearanceItems: [
      'Light keffiyeh',
      'Wind-burned face',
      'No turban',
      'One vehicle with jerrycans, no fixed generators on the strip',
      'No buildings, no permanent lights',
    ],
    networkSteps: [
      'Dirt strip “Pista Latif” — Dasht-e Margo',
      'Packed earth, two drums as a threshold',
      'Tent and vehicle well clear of the touchdown',
      'Fires only if the aircraft is coming: no lighting fit, marks only',
    ],
    networkNote: 'No long-range radio: a short transceiver. After use he covers the ruts. If used, the strip shows from the air. If left alone, the wind covers it. It is not a base: it is a threshold that exists only when he marks it.',
    relationshipItems: [
      'Bashir Achakzai — convoy lead and superior. Hwy 1 moves weight; the strip moves urgency.',
      'Haji Khairullah Barech — Zaranj crossing, the other western gate, almost a polite rival. When Zaranj is too hot Haji pushes urgent loads onto the strip; Latif resists; Bashir decides.',
      'Omar Hakimi — fighting chief. Passed Sokolov’s request to Bashir. Latif does not want a weapons aircraft on his strip.',
    ],
    weakness: 'It resupplies and makes people disappear. For aircrew it is little danger unless MANPADS that are not his appear on the strip. Medium now; high if Sokolov gets use of it.',
    treeLinkSteps: [
      'Karwan-e-Dasht (logistics)',
      'Latif Ishaqzai',
      'Strip in the Dasht-e Margo',
      'The network’s only air door',
    ],
    treeLinkNote: 'Without Latif the strip is still there, but nobody marks it at the right moment.',
  },
  hajiKhairullahBarech: {
    label: 'Haji',
    title: 'Haji Khairullah Barech',
    meta: meta(metaEn, {
      name: 'Khairullah Barech',
      nickname: '“Haji”, at the crossing',
      age: 'Unconfirmed',
      nationality: 'Afghan — Barech tribe, Nimruz',
      origin: 'Zaranj and lower Helmand',
      faction: 'Taliban — Karwan-e-Dasht',
      role: 'Border smuggling',
      category: 'Crossing / de facto customs',
      association: 'Crossing north-east of Zaranj — people, Iranian fuel, cash; not opium, not weapons',
    }),
    sections: sectionsEn,
    profile: 'Khairullah is a border man. They call him Haji at the crossing. The Barech, in Nimruz, hold water, tracks and relatives across the Iranian line. He is not a Kandahar Taliban: he is a Nimruz Taliban who accepts the network’s flag because the flag leaves him the river.\n\nIn Karwan-e-Dasht, the logistics branch, he controls a compound on the crossing north-east of Zaranj and a seasonal ford. He moves people, Iranian fuel drums, civilian spare parts, cash. He does not move Viktor Sokolov’s crates or Zahir Popalzai’s refined loads. Abdul Rahman, the treasurer, tried to buy his opium channels: he said no.',
    personality: 'He is impassive, slow, calmly insulting. He measures men by debt. He does not believe the sermons of Faisal Noor, the radio propagandist, too far away, and he does not fear Omar Hakimi, the fighting chief, too far away. He fears drones and floods. He will not host Sokolov: a Russian at the crossing is an ending.',
    appearanceItems: [
      'Bulky dark turban',
      'Heavy shawl',
      'Salt-and-pepper beard',
      'Low, steady gaze',
      'Moves little from the compound; his sons run as couriers on the ford and to the warehouses',
    ],
    networkSteps: [
      'Compound “Haji Crossing” — north-east of Zaranj, Nimruz',
      'Two low warehouses, a scale, vehicles',
      'Seasonal ford toward the river, toward the Iranian side',
      'Civilian radio, no towers, no AAA',
    ],
    networkNote: 'He pays every side of the border, enough to keep the door open. He holds hostages for debt, not prisoners of war. Closing the compound closes the network’s western door: Bashir would have to dump everything onto Hwy 1.',
    relationshipItems: [
      'Bashir Achakzai — convoy lead, counterpart, not boss. Iranian fuel for flour and spares; the crossing fills, the road distributes.',
      'Abdul Rahman — treasurer. Offered opium and was told no. Not an enemy’s no: a customs man’s no. Opium closes the crossing.',
      'Latif Ishaqzai — the other door, the Dasht-e Margo strip. Haji pushes urgent loads toward the strip when Zaranj is hot; Latif resists; Bashir decides.',
      'Samiullah Barakzai — judge. Recognised him without summoning him to the courthouse. That recognition stops Hakimi from “putting order” on the river with fighters.',
    ],
    weakness: 'A resupply, people-movement and cash-movement threat. Little danger in a fight, no AAA. If he falls, Bashir overloads Hwy 1.',
    treeLinkSteps: [
      'Karwan-e-Dasht (logistics)',
      'Haji Khairullah Barech',
      'Zaranj crossing',
      'The network’s western door',
    ],
    treeLinkNote: 'The refusal of opium and weapons is not ideology. It is how he keeps the door open.',
  },
  abdulRahman: {
    label: 'Rahman',
    title: 'Abdul Rahman',
    meta: meta(metaEn, {
      name: 'Abdul Rahman',
      nickname: 'Unconfirmed',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Helmand, Gereshk / Lashkar Gah belt',
      faction: 'Taliban — Bayt al-Mal-e-Helmand',
      role: 'Treasurer',
      category: 'Treasury / opium',
      association: 'Helmand fields; Zahir’s laboratory; network wages',
    }),
    sections: sectionsEn,
    profile: 'Rahman commands the fields, not the ambushes. He runs Bayt al-Mal-e-Helmand, the network treasury: ushr, opium paste, wages. He took Zahir Popalzai because Zahir can weigh and cut. He does not enter the laboratory: he sends a cousin to collect the refined product.\n\nHe pays families so Safi can take the sons. He pays Hakimi, and Hakimi pays Khatar. He buys food and jerrycans from Bashir Achakzai, and forbade opium paste and refined product on the trucks. He tried to buy Haji Khairullah Barech’s opium channels: he was told no.',
    personality: 'He is visibly greedy, less of an ideologue than Samiullah, more concrete than Faisal. He treats Bashir as an employee who thinks he is a partner. Samiullah gives religious cover to the ushr and keeps Zahir out of the courthouse so that, in public, the treasury stays acceptable. Rahman accepts that distance.',
    appearanceItems: [
      'Seen in the fields, not in the laboratory',
      'Does not wear the trade on his face: no vials, no glass',
      'A cousin as courier to House Shisha',
      'Received now and then in Samiullah’s compound, south-west Kandahar',
    ],
    networkSteps: [
      'Opium fields — Helmand, around Gereshk / north of Lashkar Gah',
      'Laboratory “House Shisha” — collection by cousin, Rahman does not enter',
      'Money toward Hakimi, Faisal, Safi; food and jerrycans toward Bashir',
      'Zaranj crossing closed to opium: Haji refused',
    ],
    networkNote: 'The fields grow; Zahir processes. Two sites. Refined product does not ride Bashir’s convoys. Laboratory containers, when they move, travel as warehouse goods.',
    relationshipItems: [
      'Samiullah Barakzai — judge. Rahman brings ushr; Samiullah gives the treasury religious cover and will not receive Zahir.',
      'Zahir Popalzai — laboratory chemist. Owes him a house and money; Rahman owes him the extra profit the fields cannot make alone.',
      'Omar Hakimi — fighting chief. Rahman pays wages; Hakimi keeps the cells moving.',
      'Hamidullah Safi — recruiter. Rahman pays the families. Safi hates where the money comes from, but he takes it.',
      'Bashir Achakzai — convoys. Drivers who do not ask; paste and refined product banned on the trucks.',
      'Haji Khairullah Barech — crossing. No to opium: a customs man’s no, not an enemy’s.',
    ],
    weakness: 'An indirect threat, through money. A strike on the fields or the laboratory does not stop the rifles the next day, but it delays wages and recruits. Without Rahman the treasury splits into raw paste and unpaid debts.',
    treeLinkSteps: [
      'Bayt al-Mal-e-Helmand (treasury)',
      'Abdul Rahman',
      'Fields + Zahir’s laboratory',
      'Wages for Hakimi, Faisal, Safi',
    ],
    treeLinkNote: 'Without him the fields remain, but nobody holds ushr, processing and payments together.',
  },
  omarHakimi: {
    label: 'Hakimi',
    title: 'Omar Hakimi',
    meta: meta(metaEn, {
      name: 'Omar Hakimi',
      nickname: 'Unconfirmed',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Kandahar',
      faction: 'Taliban — Lashkar-e-Maiwand',
      role: 'Fighting chief',
      category: 'Lashkar command',
      association: 'Cells, Tufan’s AAA/MANPADS, Khatar’s IEDs — fire orders',
    }),
    sections: sectionsEn,
    profile: 'Hakimi commands Lashkar-e-Maiwand, the armed branch. He issues fire orders. Samiullah covers operations with rulings; he does not tell Hakimi where to shoot. Hakimi almost never sets foot in the former courthouse: the building must not burn with him.\n\nHe pulled Tufan off ambushes and gave him AAA and MANPADS. He took Khatar’s men after the wrong vehicle and left him the bench. He buys fuel from Bashir. He takes the boys from Safi. Hotak’s warnings arrive cleaned, often without the source. He passed Sokolov’s airstrip request to Bashir: the Russian’s crates on convoys only when seizure risk is low.',
    personality: 'This is the weapons trade, not the sermon. He treats Bashir as a supplier. He does not fear Haji, too far on the river, but Samiullah recognised the crossing precisely so Hakimi would not “put order” there with fighters. He respects whoever makes the cells less visible from above.',
    appearanceItems: [
      'Compound with an exposed south wall — observed from a roof',
      'Moves with the cells, not from the judge’s compound',
      'Command radio, not Faisal’s propaganda net',
      'MANPADS and Sokolov crates pass through him, not the crossing, and not the strip (yet)',
    ],
    networkSteps: [
      'Lashkar compound — Kandahar',
      'Crest Tufan — AAA / MANPADS, south of Kandahar',
      'Khatar’s workshop — IEDs west of Gereshk; he marks the map, others plant',
      'Fuel from Karwan Compound, Hwy 1 east of Gereshk',
    ],
    networkNote: 'He does not know exactly where House Shisha is. He does not run Farid: Hotak only passes the warning. He does not introduce Sokolov to Tufan: the missiles arrive as “the brothers’ stuff”.',
    relationshipItems: [
      'Samiullah Barakzai — judge. Cover for operations, not fire orders. Hakimi at the courthouse, almost never.',
      'Nazar Mohammad Alizai (Tufan) — air defence. Without him Hakimi moves men visible to helicopters.',
      'Izatullah Noorzai (Khatar) — IEDs. Took cell command off him; left him initiators and maps.',
      'Hamidullah Safi — recruits. Boys go to the cells, not Rahman’s fields.',
      'Bashir Achakzai — fuel. A cell without jerrycans is a cell on foot. Sokolov crates banned when seizure risk is high.',
      'Rahmatullah Hotak — cleaned warnings. Hakimi often does not know where they come from.',
      'Viktor Sokolov — Russian contact. Hakimi is the cut-out: weapons yes, the Russian’s face no, the strip not yet.',
    ],
    weakness: 'A direct fire threat. If he falls, Tufan and Khatar remain trades without anyone deciding where to strike. Without Bashir’s fuel and Rahman’s wages the lashkar stops anyway.',
    treeLinkSteps: [
      'Lashkar-e-Maiwand (fighters)',
      'Omar Hakimi',
      'Fire orders',
      'Tufan / Khatar / cells',
    ],
    treeLinkNote: 'He is not the council. He is who makes the network able to shoot. Without him there are rulings, money and radio, and few coordinated ambushes.',
  },
  faisalNoor: {
    label: 'Faisal',
    title: 'Faisal Noor',
    meta: meta(metaEn, {
      name: 'Faisal Noor',
      nickname: 'Unconfirmed',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Kandahar',
      faction: 'Taliban — Sada-ye-Maiwand',
      role: 'Radio propagandist',
      category: 'Propaganda',
      association: 'Radio net and towers; courtyard rulings read on air',
    }),
    sections: sectionsEn,
    profile: 'Faisal is the voice, not the courtyard. He runs propaganda in the Sada-ye-Maiwand branch. Hamidullah Safi is a branch-mate, not a subordinate: radio prepares the villages, the courtyard collects whoever stands up. Safi refused to become the second voice, because radio would burn him.\n\nHe takes the rulings posted in Samiullah’s courtyard and reads them on air. He does not enter the former courthouse: the voice is already recognisable, and the building must not burn with him. Hotak cannot stand the noise. Tufan envies a voice that travels far without being shot at.',
    personality: 'He is theatrical, vulgar to the judge, too far away for Haji. He ignores Bashir. He believes the sermons more than Rahman. He is not a fighting chief and does not keep a cell.',
    appearanceItems: [
      'Microphone, not a rifle in the foreground',
      'Radio towers, not the civilian aerial on the courthouse roof',
      'A voice recognisable on the air',
      'Not seen in Samiullah’s compound',
    ],
    networkSteps: [
      'Towers / Sada-ye-Maiwand radio net — Kandahar and around',
      'Rulings from the former courthouse courtyard, read on air',
      'Villages prepared; recruits collected by Safi in Khakrez',
      'No bridge to Hotak’s repeater or Bashir’s civilian radio',
    ],
    networkNote: 'The aerial on the judge’s building is leftover civilian kit, short range, not his net. Without Safi he talks to a network that does not renew itself. Without Tufan the towers sit more exposed to whoever flies low.',
    relationshipItems: [
      'Samiullah Barakzai — judge. Faisal reads the rulings; Samiullah finds him vulgar and keeps him out of the compound.',
      'Hamidullah Safi — same branch. Radio and courtyard. Faisal is not his boss.',
      'Rahmatullah Hotak — intelligence. Cannot stand noise, Faisal first of all.',
      'Nazar Mohammad Alizai (Tufan) — envies the voice. The towers sit under his sky.',
      'Omar Hakimi — takes men the radio has warmed and Safi has delivered.',
      'Haji Khairullah Barech — does not believe the sermons, too far from the river.',
    ],
    weakness: 'A threat of influence, not of fire. If the towers fall, villages stop arriving already convinced. If Safi falls, the voice remains and the recruit flow does not.',
    treeLinkSteps: [
      'Sada-ye-Maiwand (propaganda / recruitment)',
      'Faisal Noor',
      'Radio towers',
      'Villages prepared for Safi and Hakimi',
    ],
    treeLinkNote: 'Without him Safi speaks only in the courtyard and Samiullah’s rulings stay on the wall.',
  },
  viktorSokolov: {
    label: 'Sokolov',
    title: 'Viktor Sokolov',
    meta: meta(metaEn, {
      name: 'Viktor Sokolov',
      nickname: 'Unconfirmed',
      age: 'Unconfirmed',
      nationality: 'Russian',
      origin: 'Unconfirmed',
      faction: 'Arms contact — outside the Taliban network',
      role: 'Weapons supplier',
      category: 'External resupply / MANPADS',
      association: 'Cut-out: Omar Hakimi. Banned from the courthouse, the crossing, and the strip until Bashir says yes',
    }),
    sections: sectionsEn,
    profile: 'Sokolov is not Taliban. He is the Russian arms contact. Tufan’s MANPADS pass through Hakimi and arrive as “the brothers’ stuff”: Tufan has never met him. Khatar does not want initiators from his network.\n\nHe has asked for Latif Ishaqzai’s dirt strip in the Dasht-e Margo. Hakimi took that request to Bashir. Bashir has not said yes yet. Latif does not want a weapons aircraft on the strip. Samiullah forbade him from setting foot in the former courthouse. Haji will not host him at the crossing: a Russian there is an ending.',
    personality: 'He stays out of the compound, off the river, off the ridge. The trade is the cut-out: Hakimi sees crates, everyone else sees “the brothers”. He does not preach, does not pay ushr, does not command cells.',
    appearanceItems: [
      'Not observed at the courthouse, the crossing, or Crest Tufan',
      'No fixed signature in Helmand or Kandahar in this file',
      'Crates meant for Hakimi, not for Bashir when seizure risk is high',
      'Open request for Pista Latif — not authorised',
    ],
    networkSteps: [
      'Entry: Hakimi, Lashkar-e-Maiwand',
      'Out to Tufan: MANPADS, origin covered',
      'Bashir’s convoys: crates only if Hakimi allows it and risk is low',
      'Dasht-e Margo strip and Zaranj crossing: still no',
    ],
    networkNote: 'If he gets the strip, the dirt runway becomes a weapons door and the air threat rises. As long as Bashir says no, Sokolov remains a pipe into Hakimi, not a base.',
    relationshipItems: [
      'Omar Hakimi — the only useful cut-out in this file. Weapons yes, face no.',
      'Nazar Mohammad Alizai (Tufan) — receives the MANPADS without knowing the Russian.',
      'Izatullah Noorzai (Khatar) — refuses “brothers’” initiators.',
      'Bashir Achakzai / Latif Ishaqzai — convoys and strip: seizure and visual marks. Still closed or conditional.',
      'Samiullah Barakzai — banned from the building where judgments are made.',
      'Haji Khairullah Barech — banned from the crossing.',
    ],
    weakness: 'A resupply threat, especially MANPADS. On his own he holds no ridge. Cut Hakimi and you cut Sokolov. Open the strip and the file’s value jumps.',
    treeLinkSteps: [
      'Sokolov (external)',
      'Omar Hakimi',
      'Crates / MANPADS',
      'Tufan, not the crossing, not the strip (yet)',
    ],
    treeLinkNote: 'Outside the Shura. Inside the sky, if the missiles arrive. Without Hakimi he has no useful Taliban recipient.',
  },
  faridAhmadKhan: {
    label: 'Farid',
    title: 'Farid Ahmad Khan',
    meta: meta(metaEn, {
      name: 'Farid Ahmad Khan',
      nickname: 'Unconfirmed',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Kandahar — seen in the market district',
      faction: 'Paid source — not affiliated with the network',
      role: 'Source for Rahmatullah Hotak',
      category: 'HUMINT',
      association: 'Hotak only; used-phone seller as go-between; never the same room',
    }),
    sections: sectionsEn,
    profile: 'Farid is not Taliban. He is a paid source. The only contact in the network is Rahmatullah Hotak, Daftar-e-Khabar. They are never in the same room: a used-phone seller in the city passes messages and payments.\n\nHe sells movements, timings, checkpoints. Hotak cleans the take and sends it to Hakimi as early warning and to Bashir as route advice, often without saying where it came from. Hotak pays him, holds him with a surveillance photograph — Farid caught where he should not be — and does not respect him.',
    personality: 'The relationship is dirty on both sides. Farid does not enter the courthouse, does not speak on the radio, does not plant IEDs. When he appears to be on duty, the Crest Karg repeater stays off: Hotak will not transmit while the source is exposed.',
    appearanceItems: [
      'Male, market district, at least one pass at 06:14 local',
      'No commander’s turban, no rifle in this file',
      'Not observed on Crest Karg or in Samiullah’s compound',
      'Contact only through the go-between',
    ],
    networkSteps: [
      'Used-phone seller — city, the cut between Farid and Hotak',
      'Payments and messages, never a direct meeting',
      'Hotak, Crest Karg / valley safe house, Arghandab',
      'Out: warnings to Hakimi, routes to Bashir',
    ],
    networkNote: 'Without Hotak the source has no useful recipient in the network. Without Farid, Hotak loses the dirtiest and most useful piece. Hakimi must not know the name.',
    relationshipItems: [
      'Rahmatullah Hotak — sole Taliban handler. Pays, blackmails, does not respect.',
      'Omar Hakimi — receives cleaned warnings, often without the source.',
      'Bashir Achakzai — gets checkpoint advice; in return truck movements go to Hotak.',
      'Samiullah Barakzai — sees only what Hotak selects. Does not handle Farid.',
    ],
    weakness: 'An information threat, not a fire threat. Burn Farid and early warning goes blind. Burn Hotak and Farid has nobody to sell to. The blackmail photograph is also a signature: if it gets out, the source dies as an asset.',
    treeLinkSteps: [
      'Farid Ahmad Khan (paid source)',
      'Go-between (used phones)',
      'Rahmatullah Hotak',
      'Warnings to Hakimi and Bashir',
    ],
    treeLinkNote: 'He is not a branch of the network. He is a pipe. If the pipe breaks, the lashkar stays armed and goes blind.',
  },
  afghanistanChart: {
    label: 'Afghanistan',
    title: 'Operational chart — Afghanistan',
    body: 'Theatre operational map. No strings on the chart: geographic reference for Kandahar, Helmand, Hwy 1, Dasht-e Margo and Zaranj.',
  },
};
