const metaIt = {
  name: 'Nome',
  nickname: 'Soprannome',
  age: 'Età',
  nationality: 'Nazionalità',
  origin: 'Origine',
  faction: 'Fazione',
  role: 'Ruolo',
  category: 'Categoria',
  association: 'Associazione',
};

const metaEn = {
  name: 'Name',
  nickname: 'Nickname',
  age: 'Age',
  nationality: 'Nationality',
  origin: 'Origin',
  faction: 'Faction',
  role: 'Role',
  category: 'Category',
  association: 'Association',
};

const sectionsIt = {
  profile: 'Profilo',
  personality: 'Personalità',
  appearance: 'Aspetto',
  network: 'Dispositivo operativo',
  relationships: 'Relazioni',
  weakness: 'Valutazione della minaccia',
  treeLink: 'Ruolo nella storyline',
};

const sectionsEn = {
  profile: 'Profile',
  personality: 'Personality',
  appearance: 'Appearance',
  network: 'Operational picture',
  relationships: 'Relationships',
  weakness: 'Threat assessment',
  treeLink: 'Role in the storyline',
};

function meta(labels, values) {
  return Object.fromEntries(
    Object.keys(values).map((key) => [key, { label: labels[key], value: values[key] }]),
  );
}

export const lidcWhiteboardItemsIt = {
  samiullahBarakzai: {
    label: 'Sangsar',
    title: 'Maulvi Samiullah Barakzai — "Sangsar"',
    meta: meta(metaIt, {
      name: 'Samiullah Barakzai',
      nickname: '"Sangsar" — La Roccia',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Distretto di Panjwai, Kandahar',
      faction: 'Talebani — Shura-ye-Sangsar',
      role: 'Giudice e coordinatore politico-religioso',
      category: 'Direzione politico-religiosa',
      association: 'Tribunale distrettuale occupato',
    }),
    sections: sectionsIt,
    profile: 'Samiullah viene da una famiglia di mullah di Panjwai, non da una famiglia di comandanti. Ha studiato in madrasa a Kandahar e per anni ha scritto sentenze su terre, debiti e faide, senza mai guidare un’imboscata. Le altre correnti lo accettano al tavolo proprio per questo: non chiede il comando dei combattenti.\n\nPresiede la Shura-ye-Sangsar, il consiglio che tiene insieme tesoreria, forze armate, propaganda e logistica. Chi ignora il consiglio, almeno sulla carta, perde i soldi di Abdul Rahman e le reclute di Hamidullah Safi. Non dà ordini di fuoco a Omar Hakimi: il suo lavoro è far sì che le cinque correnti restino una sola organizzazione.',
    personality: 'È lento, formale e vanitoso da religioso. Parla poco, corregge gli altri e non alza la voce. Gli stranieri, per lui, non sono un bersaglio da colpire: sono un problema da tenere fuori dal tribunale. Sokolov non deve mettere piede lì. Teme una sentenza sbagliata più di un attacco aereo, perché una sentenza sbagliata gli fa perdere i capivillaggio.',
    appearanceItems: [
      'Si muove poco dal recinto del tribunale',
      'Non porta armi lunghe',
      'Scorta leggera all’ingresso',
      'Non usa il telefono satellitare',
      'Sentenze scritte a mano, affisse nel cortile',
    ],
    networkSteps: [
      'Tribunale distrettuale occupato — sud-ovest di Kandahar',
      'Cortile, stanza delle udienze, antenna civile sul tetto',
      'Messaggeri, non radio',
      'Rapporti informativi tramite Rahmatullah Hotak',
    ],
    networkNote: 'L’antenna civile serve solo a collegamenti corti, non alla rete radio di Faisal. Rahman viene ricevuto ogni tanto, Hakimi quasi mai. Faisal Noor non entra: la sua voce in radio è già troppo esposta.',
    relationshipItems: [
      'Rahmatullah Hotak — raccoglie le informazioni al posto suo. In cambio ottiene la protezione del consiglio.',
      'Abdul Rahman — porta i soldi dell’ushr. Samiullah dà alla tesoreria un riconoscimento religioso.',
      'Omar Hakimi — comanda i combattenti. Il giudice gli dà la copertura delle operazioni, non gli ordini di fuoco.',
      'Faisal Noor — prende le sentenze del cortile e le legge in radio. Samiullah lo trova volgare, ma sa che la radio arriva lontano.',
      'Hamidullah Safi — lo benedice in pubblico: le reclute arrivano con il riconoscimento del consiglio.',
    ],
    weakness: 'Non pianifica imboscate. Se resta al suo posto la rete resta unita. Se viene a mancare, le correnti si separano.',
    treeLinkSteps: [
      'Shura-ye-Sangsar',
      'Samiullah Barakzai',
      'Copertura religiosa',
      'Cinque correnti tenute insieme',
    ],
    treeLinkNote: 'Senza Samiullah le cinque correnti restano cinque mestieri uno accanto all’altro. Non è un comandante militare, ma tiene insieme l’organizzazione sul piano politico.',
  },
  rahmatullahHotak: {
    label: 'Karg',
    title: 'Rahmatullah Hotak — "Karg"',
    meta: meta(metaIt, {
      name: 'Rahmatullah Hotak',
      nickname: '"Karg" — Il Corvo',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Distretto di Arghandab, Kandahar',
      faction: 'Talebani — Shura-ye-Sangsar / Daftar-e-Khabar',
      role: 'Capo dei servizi informativi',
      category: 'Intelligence',
      association: 'Handler di Farid Ahmad Khan',
    }),
    sections: sectionsIt,
    profile: 'Hotak è cresciuto ad Arghandab facendo il corriere e poi l’informatore. Non ha mai guidato una cellula armata. I pastori lo chiamano Karg perché lo vedono sulle creste e poi non c’è più.\n\nDirige i servizi informativi del consiglio. È l’unico talebano autorizzato a gestire Farid Ahmad Khan: non come un amico, come una fonte. Quello che Farid vende diventa avvisi per Omar Hakimi e indicazioni di percorso per Bashir Achakzai.',
    personality: 'È taciturno, sospettoso, quasi superstizioso. Conta le cose. Non alza la voce e non fa discorsi. Non sopporta chi fa rumore, Faisal per primo. Con Farid il rapporto è sporco: lo paga, lo tiene sotto ricatto, non lo stima.',
    appearanceItems: [
      'Berretto pakol, non turbante',
      'Binocolo, taccuino, ripetitore debole',
      'Evita la via principale',
      'Ripetitore spento in coincidenza sospetta con i turni di Farid',
    ],
    networkSteps: [
      'Posto di osservazione «Cresta Karg»',
      'Colline a nord-ovest di Arghandab',
      'Riparo in pietra, telo, ripetitore basso',
      'Intermediario in città: venditore di telefoni usati',
    ],
    networkNote: 'Incontra Farid solo attraverso l’intermediario. I due non si trovano mai nella stessa stanza. Dorme a valle, in una casa sicura, non sul posto di osservazione.',
    relationshipItems: [
      'Samiullah Barakzai — unico superiore. Hotak gli porta le notizie già selezionate.',
      'Farid Ahmad Khan — fonte più utile e più sporca. Fotografia di sorveglianza usata come ricatto.',
      'Omar Hakimi — riceve avvisi già puliti, spesso senza sapere da dove arrivano.',
      'Bashir Achakzai — compra indicazioni sui posti di blocco; in cambio passa i movimenti dei camion.',
    ],
    weakness: 'Minaccia di informazioni, non di fuoco. Senza di lui i combattenti restano armati, ma perdono i preavvisi.',
    treeLinkSteps: [
      'Farid Ahmad Khan',
      'Rahmatullah Hotak',
      'Consiglio',
      'Preavvisi a Hakimi e Bashir',
    ],
    treeLinkNote: 'È il ponte tra Farid Khan e i Talebani. Senza di lui la talpa non ha un destinatario utile, e il consiglio perde le informazioni.',
  },
  hamidullahSafi: {
    label: 'Ustad',
    title: 'Hamidullah Safi — "Ustad"',
    meta: meta(metaIt, {
      name: 'Hamidullah Safi',
      nickname: '«Ustad», tra i ragazzi',
      age: '29 anni',
      nationality: 'Afghana',
      origin: 'Distretto di Khakrez, Kandahar',
      faction: 'Talebani — Sada-ye-Maiwand',
      role: 'Reclutatore',
      category: 'Reclutamento',
      association: 'Madrasa di villaggio',
    }),
    sections: sectionsIt,
    profile: 'Safi ha ventinove anni e una voce da cortile. Figlio di un imam di villaggio a Khakrez, ha imparato a parlare ai ragazzini prima che a sparare. Non è un propagandista: non sta al microfono. Non è un comandante: non tiene una cellula. Porta i ragazzi fino al cancello e poi li lascia.\n\nTrova, convince, sposta. Lavora su debiti di famiglia, vendette, fame e orgoglio. Rahman paga le famiglie. Ha rifiutato di diventare la seconda voce di Faisal, perché la radio lo brucerebbe.',
    personality: 'È carismatico in modo giovane, non teatrale come Faisal. Crede in quello che dice più di Rahman e meno di Samiullah. Si infastidisce se lo chiamano soldato. Ha paura di Hotak, perché una lista di nomi in mano ai servizi informativi è una condanna.',
    appearanceItems: [
      'Giovane, barba nera',
      'Gilet nero su kameez bianco',
      'Niente turbante',
      'Niente armi lunghe in sede',
      'Furgone bianco con un paraurti riparato',
    ],
    networkSteps: [
      'Madrasa «Cortile Safi» — nord di Kandahar, Khakrez',
      'Edificio a un piano, albero, recinto',
      'Lezioni nel cortile, partenze a villaggio quieto',
      'Armi solo dopo, dalla lashkar',
    ],
    networkNote: 'Non è un campo di addestramento. Evita Gereshk e l’Helmand, perché lì i ragazzi finiscono nei campi di Rahman invece che nelle cellule.',
    relationshipItems: [
      'Faisal Noor — compagno di corrente, non capo. La radio prepara, il cortile raccoglie.',
      'Omar Hakimi — dove finiscono i ragazzi. In cambio Safi ottiene che non finiscano nei campi.',
      'Abdul Rahman — paga le famiglie. Safi odia che quei soldi vengano dall’oppio, ma li prende.',
      'Samiullah Barakzai — lo benedice in pubblico e in privato lo trova troppo acceso.',
    ],
    weakness: 'Minaccia di uomini nuovi, non di fuoco. Se la madrasa si chiude, si ferma il flusso verso Hakimi.',
    treeLinkSteps: [
      'Sada-ye-Maiwand',
      'Hamidullah Safi',
      'Cortile / madrasa',
      'Reclute verso Hakimi',
    ],
    treeLinkNote: 'Senza Safi, Hakimi consuma i villaggi e Faisal parla a una rete che non si rinnova.',
  },
  zahirPopalzai: {
    label: 'Shisha',
    title: 'Zahir Popalzai — "Shisha"',
    meta: meta(metaIt, {
      name: 'Zahir Popalzai',
      nickname: '"Shisha"',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Nord di Lashkar Gah, Helmand',
      faction: 'Talebani — Bayt al-Mal-e-Helmand',
      role: 'Supervisore del laboratorio clandestino',
      category: 'Tesoreria / trasformazione',
      association: 'Laboratorio, non coltivazione',
    }),
    sections: sectionsIt,
    profile: 'Zahir non è un signore dell’oppio. È un ex insegnante di chimica di Lashkar Gah. Rahman lo ha preso perché sa pesare, non perché sa sparare. Il soprannome Shisha viene dai tubi di vetro del laboratorio.\n\nÈ l’unico responsabile della trasformazione nella rete di Rahman. Riceve pasta d’oppio e restituisce prodotto già lavorato. Non comanda i campi e non porta i carichi al confine.',
    personality: 'È ansioso e istruito. Non è un ideologo. Ha più paura di Rahman che della coalizione. Fuma in continuazione, dita gialle. Samiullah lo considera impuro: quella distanza la vogliono sia Rahman sia il giudice.',
    appearanceItems: [
      'Cuffia da preghiera, niente turbante',
      'Dita gialle di nicotina',
      'Esce di rado',
      'Quaderni di scuola per i pesi',
    ],
    networkSteps: [
      'Laboratorio «Casa Shisha» — nord di Lashkar Gah',
      'Casa recintata tra i campi e un canale',
      'Teli di plastica, bidoni, generatore, fossa di scarico',
      'Due aiutanti, non armati',
    ],
    networkNote: 'Rahman non entra: manda un cugino a ritirare. Hakimi non sa esattamente dove sia. Il laboratorio e i campi sono due cose diverse.',
    relationshipItems: [
      'Abdul Rahman — padrone. Zahir gli deve casa e soldi; Rahman gli deve il guadagno extra dei campi.',
      'Bashir Achakzai — ha portato solvente e fatto troppe domande. Ora i contenitori arrivano come merce di magazzino.',
      'Samiullah Barakzai — non lo riceve. In pubblico la tesoreria resta accettabile perché il laboratorio resta invisibile.',
    ],
    weakness: 'Minaccia indiretta, attraverso i soldi. Un colpo al laboratorio taglia il guadagno di Rahman e ritarda gli stipendi.',
    treeLinkSteps: [
      'Campi di Rahman',
      'Zahir Popalzai',
      'Laboratorio',
      'Denaro per Hakimi, Faisal, Safi',
    ],
    treeLinkNote: 'Senza di lui la tesoreria vende pasta d’oppio grezza, con meno guadagno e più gente in mezzo.',
  },
  nazarMohammadAlizai: {
    label: 'Tufan',
    title: 'Nazar Mohammad Alizai — "Tufan"',
    meta: meta(metaIt, {
      name: 'Nazar Mohammad Alizai',
      nickname: '"Tufan" — Tempesta',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Distretto di Dand, Kandahar',
      faction: 'Talebani — Lashkar-e-Maiwand',
      role: 'Responsabile della contraerea',
      category: 'Difesa aerea tattica',
      association: 'Batteria AAA / MANPADS',
    }),
    sections: sectionsIt,
    profile: 'Alizai ha fatto il mitragliere su veicoli scoperti per anni. Un elicottero gli ha ucciso il fratello; da allora il cielo è il suo lavoro. Hakimi lo ha tolto dalle imboscate perché a terra sprecava munizioni e contro gli aerei le usava bene.\n\nÈ l’unico referente della lashkar per la minaccia aerea a bassa quota. Cannoni trainati, mitragliere pesanti e pochi missili a spalla arrivati — senza che lui lo sappia con certezza — dalla rete di Sokolov attraverso Hakimi.',
    personality: 'È testardo, rancoroso e semplice. Tratta il cielo come un nemico personale. Rispetta Hakimi perché gli ha dato i missili. Invidia Faisal, la cui voce arriva lontano senza farsi sparare. Mastica naswar. Prega guardando in su.',
    appearanceItems: [
      'Niente turbante',
      'Giacca mimetica sopra il kameez',
      'Sguardo stretto, spesso contro luce',
      'Sposta i pezzi in un raggio breve intorno alla cresta',
    ],
    networkSteps: [
      'Batteria «Cresta Tufan» — sud di Kandahar',
      'Pezzi trainati, sacchi di terra, teloni',
      'Veicolo con mitragliatrice',
      'Nascondigli per i missili e pezzi finti',
    ],
    networkNote: 'Usa osservatori a valle, non quelli di Hotak: i due si coprono la stessa zona e si evitano. Dorme in una cava a mezza costa.',
    relationshipItems: [
      'Omar Hakimi — gli ha dato questo mestiere e i missili. Senza Tufan, Hakimi muove uomini visibili dall’alto.',
      'Viktor Sokolov — non lo ha mai incontrato. I missili arrivano come «roba dei fratelli».',
      'Bashir Achakzai — i camion alzano polvere e gli coprono la vista. Conflitto di mestiere, non di consiglio.',
    ],
    weakness: 'Minaccia aerea diretta: contraerea e missili a spalla. Nessun peso politico. Senza la batteria, tribunale, torri e rifugi restano più esposti.',
    treeLinkSteps: [
      'Lashkar-e-Maiwand',
      'Nazar Mohammad Alizai',
      'Cresta Tufan',
      'Cielo a bassa quota più costoso',
    ],
    treeLinkNote: 'Il suo lavoro rende costoso volare bassi su Kandahar, sulle torri di Faisal e sul tribunale di Samiullah.',
  },
  izatullahNoorzai: {
    label: 'Khatar',
    title: 'Izatullah Noorzai — "Khatar"',
    meta: meta(metaIt, {
      name: 'Izatullah Noorzai',
      nickname: '"Khatar"',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Distretto di Gereshk, Helmand',
      faction: 'Talebani — Lashkar-e-Maiwand',
      role: 'Responsabile delle mine e degli IED',
      category: 'Guerra mine',
      association: 'Officina clandestina',
    }),
    sections: sectionsIt,
    profile: 'Noorzai è un meccanico di strada. Ha imparato a costruire mine dopo esserci rimasto sotto: gli mancano due dita della mano sinistra. Hakimi gli ha vietato di comandare una cellula dopo che un suo gruppo ha fatto saltare il veicolo sbagliato.\n\nProduce cariche, inneschi, mine anticarro artigianali e trappole. Non decide dove colpire. Riceve un segno su una mappa da un uomo di Hakimi e prepara il pezzo. I combattenti mettono gli ordigni a terra. Lui li costruisce.',
    personality: 'È irritabile, superstizioso e scortese. Ce l’ha con Hakimi per avergli tolto gli uomini, ma obbedisce. Non sopporta Zahir Popalzai: l’odore del laboratorio gli ricorda i fumi sbagliati. Non vuole inneschi arrivati dalla rete di Sokolov.',
    appearanceItems: [
      'Mano sinistra mutilata',
      'Non porta turbante',
      'Bruciatura sul collo',
      'Generatore udibile quando è acceso',
    ],
    networkSteps: [
      'Officina «Fattoria Khatar» — ovest di Gereshk',
      'Capannone, batterie, cavi, fertilizzante, generatore',
      'Spostamento su motocarro',
      'Comunicazione con biglietti, non radio',
    ],
    networkNote: 'Evita i convogli di Bashir quando può: un sequestro di carburante non deve portare agli inneschi. Il materiale non resta a lungo: esce verso le cellule.',
    relationshipItems: [
      'Omar Hakimi — superiore. Gli ha tolto gli uomini e gli ha lasciato il bancone, le mappe e chi pianta gli ordigni.',
      'Bashir Achakzai — a pagamento gli nasconde qualche cassa tra i ricambi, e può rifiutare quando il rischio è alto.',
      'Abdul Rahman — paga Hakimi, Hakimi paga Khatar. Izatullah non vuole l’oppio vicino al fertilizzante.',
    ],
    weakness: 'Pericoloso per elicotteri a bassa quota e per chi si muove a terra. Pericoloso dall’aria, da solo, poco. Hakimi può sostituirlo, ma non in fretta.',
    treeLinkSteps: [
      'Lashkar-e-Maiwand',
      'Izatullah Noorzai',
      'Officina IED',
      'Piste pericolose senza imboscata',
    ],
    treeLinkNote: 'Importante sul terreno, irrilevante in politica. Se viene meno, la lashkar perde chi rende pericolose le strade anche dove non c’è un’imboscata.',
  },
  bashirAchakzai: {
    label: 'Karwan',
    title: 'Bashir Achakzai — "Karwan"',
    meta: meta(metaIt, {
      name: 'Bashir Achakzai',
      nickname: '"Karwan" — La Carovana',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Fascia Achakzai di Spin Boldak, Kandahar',
      faction: 'Talebani — Karwan-e-Dasht',
      role: 'Responsabile dei convogli',
      category: 'Logistica',
      association: 'Carburante, viveri, ricambi — non oppio, non armi Sokolov',
    }),
    sections: sectionsIt,
    profile: 'Bashir è un mercante prima che un talebano. Gli Achakzai tengono le strade. Lui tiene i camion. Rahman lo ha preso perché i suoi autisti non fanno domande. Hakimi lo usa perché una cellula senza carburante è una cellula a piedi.\n\nOrganizza i convogli sulla via principale e sulle piste parallele: carburante, farina, ricambi, generatori, a volte contanti. Rahman gli ha vietato di caricare pasta d’oppio. Hakimi gli ha vietato le casse di Sokolov quando il rischio di sequestro è alto.',
    personality: 'È calcolatore, cordiale, avido in modo visibile, con un sorriso da mercato. Non fa prediche. Samiullah lo tollera. Faisal lo ignora. Hakimi lo tratta da fornitore. Rahman da dipendente che si crede socio.',
    appearanceItems: [
      'Gilet ricamato',
      'Anello d’oro',
      'Barba curata',
      'Non mostra il fucile',
      'Autisti afghani, targhe miste, teloni sporchi',
    ],
    networkSteps: [
      'Magazzino «Recinto Karwan» — via principale a est di Gereshk',
      'Tettoie, camion, cisterne, officina minima',
      'Convogli corti, tre o sei veicoli',
      'Radio civile, non quella di Faisal',
    ],
    networkNote: 'Sta al recinto come un padrone di ditta e ha casa nel bazar di Gereshk. I suoi uomini sanno cosa non devono caricare.',
    relationshipItems: [
      'Abdul Rahman — gli compra viveri e taniche, e il diritto di non toccare l’oppio.',
      'Omar Hakimi — gli compra il carburante che tiene in piedi le cellule.',
      'Rahmatullah Hotak — vende indicazioni sui posti di blocco e compra i movimenti dei camion.',
      'Latif Ishaqzai — riceve ricambi e carichi leggeri quando la via principale è troppo sorvegliata.',
      'Haji Khairullah Barech — scambia carichi al valico: taniche iraniane contro viveri, persone contro commissioni.',
      'Izatullah Noorzai — a volte un passaggio per gli inneschi, a pagamento e senza guardare dentro.',
    ],
    weakness: 'Minaccia logistica. Un colpo sul magazzino ferma il ritmo. Un colpo su un solo camion ferma un viaggio.',
    treeLinkSteps: [
      'Karwan-e-Dasht',
      'Bashir Achakzai',
      'Convogli',
      'Hakimi a piedi / Rahman senza viveri, se cade',
    ],
    treeLinkNote: 'Senza di lui le altre correnti restano chiuse nel proprio distretto. Alta importanza: la rete diventa lenta e locale.',
  },
  latifIshaqzai: {
    label: 'Pista',
    title: 'Latif Ishaqzai — "Pista"',
    meta: meta(metaIt, {
      name: 'Latif Ishaqzai',
      nickname: '"Pista"',
      age: 'Non confermata',
      nationality: 'Afghana',
      origin: 'Distretto di Dishu, Dasht-e Margo',
      faction: 'Talebani — Karwan-e-Dasht',
      role: 'Gestore della pista d’atterraggio improvvisata',
      category: 'Logistica aerea improvvisata',
      association: 'Striscia in terra nel deserto',
    }),
    sections: sectionsIt,
    profile: 'Latif ha passato la vita a leggere il deserto: suolo, vento, sale. Non è un pilota e non è un trafficante di oppio. Dice dove si può atterrare e accende due fuochi.\n\nÈ il responsabile della pista in terra nel Dasht-e Margo. I carichi sono leggeri: ricambi, denaro, persone, a volte un tecnico. Sokolov ha chiesto di usarla. Latif ha riferito a Bashir, e Bashir non ha ancora detto di sì.',
    personality: 'È solitario, secco, poco interessato al consiglio. Parla del vento come Tufan parla del cielo, ma in orizzontale. Tiene Rahman lontano, perché l’oppio attira occhi nel deserto. Rispetta Barech, perché il valico è un mestiere simile.',
    appearanceItems: [
      'Kefiah chiara',
      'Viso bruciato dal vento',
      'Niente turbante',
      'Un veicolo con taniche',
      'Niente generatori fissi',
    ],
    networkSteps: [
      'Pista in terra «Pista Latif» — Dasht-e Margo',
      'Striscia battuta, due fusti come soglia',
      'Tenda e veicolo lontano, niente edifici',
      'Fuochi solo se l’aereo sta arrivando',
    ],
    networkNote: 'Niente radio lunga: una ricetrasmittente corta. Dopo aver finito copre i solchi. Se usata si vede bene. Se lasciata stare, il vento la copre.',
    relationshipItems: [
      'Bashir Achakzai — superiore. La via principale muove il peso, la pista muove l’urgenza.',
      'Haji Khairullah Barech — l’altro varco a ovest, quasi un rivale educato. Quando Zaranj si sporca, qualcuno tenta di scaricare sulla pista.',
      'Omar Hakimi — ha fatto arrivare a Bashir la richiesta di Sokolov. Latif non vuole un aereo di armi sulla striscia.',
    ],
    weakness: 'Serve a rifornire e a far sparire persone. Per chi vola è poco pericolosa, a meno che sulla pista non arrivino missili che non sono suoi.',
    treeLinkSteps: [
      'Karwan-e-Dasht',
      'Latif Ishaqzai',
      'Pista nel deserto',
      'Unica porta aerea della rete',
    ],
    treeLinkNote: 'Media adesso, alta se Sokolov ottiene l’uso. Senza Latif la striscia c’è ancora, ma nessuno la marca al momento giusto.',
  },
  hajiKhairullahBarech: {
    label: 'Haji',
    title: 'Haji Khairullah Barech',
    meta: meta(metaIt, {
      name: 'Khairullah Barech',
      nickname: '«Haji», al valico',
      age: 'Non confermata',
      nationality: 'Afghana — tribù Barech, Nimruz',
      origin: 'Zaranj e Helmand inferiore',
      faction: 'Talebani — Karwan-e-Dasht',
      role: 'Contrabbando di frontiera',
      category: 'Valico / dogana di fatto',
      association: 'Persone, carburante iraniano, contante — non oppio, non armi',
    }),
    sections: sectionsIt,
    profile: 'Haji Khairullah è un uomo di frontiera. I Barech tengono acqua, piste e parenti oltre il confine. Non è un talebano di Kandahar: è un talebano di Nimruz che accetta la bandiera perché la bandiera gli lascia il fiume.\n\nControlla un recinto sul valico e un guado stagionale. Fa passare persone, taniche di carburante iraniano, pezzi di ricambio civili, contante. Non fa passare le casse di Sokolov né i carichi di Zahir. Rahman ha tentato di comprargli i canali per l’oppio: ha detto di no.',
    personality: 'È impassibile, lento, offensivo con calma. Misura gli uomini dal debito. Non crede alle prediche di Faisal, troppo lontane, e non teme Hakimi, troppo lontano. Teme i droni e le inondazioni. Non ospita Sokolov: un russo al valico è una fine.',
    appearanceItems: [
      'Turbante scuro voluminoso',
      'Scialle pesante',
      'Barba brizzolata',
      'Sguardo basso e fermo',
      'Si muove poco; i figli fanno i corrieri',
    ],
    networkSteps: [
      'Recinto «Valico Haji» — nord-est di Zaranj',
      'Due magazzini bassi, bilancia, veicoli',
      'Guado stagionale verso il fiume',
      'Radio civile, niente torri, niente contraerea',
    ],
    networkNote: 'Paga tutti i lati. Tiene ostaggi per debiti, non prigionieri di guerra. Chiudere il recinto chiude la porta ovest.',
    relationshipItems: [
      'Bashir Achakzai — corrispondente, non capo. Taniche iraniane contro farina e ricambi; il valico riempie, la strada distribuisce.',
      'Abdul Rahman — gli ha offerto l’oppio e si è sentito rispondere di no. Non è un no da nemico, è un no da doganiere.',
      'Latif Ishaqzai — l’altra porta. Haji spinge, Latif resiste, Bashir decide.',
      'Samiullah Barakzai — lo ha riconosciuto senza convocarlo. Quel riconoscimento impedisce a Hakimi di «mettere ordine» sul fiume.',
    ],
    weakness: 'Minaccia di rifornimento, di passaggio persone e di movimento di contante. Poco pericoloso in combattimento. Se cade, Bashir sovraccarica la via principale.',
    treeLinkSteps: [
      'Karwan-e-Dasht',
      'Haji Khairullah Barech',
      'Valico di Zaranj',
      'Porta ovest della rete',
    ],
    treeLinkNote: 'Il rifiuto dell’oppio e delle armi non è ideologia. È il modo in cui tiene aperta la porta.',
  },
  afghanistanChart: {
    label: 'Afghanistan',
    title: 'Carta operativa — Afghanistan',
    body: 'Mappa operativa del teatro. Nessun filo sulla carta: riferimento geografico per Kandahar, Helmand, Hwy 1, Dasht-e Margo e Zaranj.',
  },
};

export const lidcWhiteboardItemsEn = {
  samiullahBarakzai: {
    label: 'Sangsar',
    title: 'Maulvi Samiullah Barakzai — "Sangsar"',
    meta: meta(metaEn, {
      name: 'Samiullah Barakzai',
      nickname: '"Sangsar" — The Rock',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Panjwai District, Kandahar',
      faction: 'Taliban — Shura-ye-Sangsar',
      role: 'Judge and political-religious coordinator',
      category: 'Political-religious direction',
      association: 'Occupied district court',
    }),
    sections: sectionsEn,
    profile: 'Samiullah comes from a family of mullahs in Panjwai, not a family of commanders. He studied in a Kandahar madrasa and spent years writing rulings on land, debt and feuds without ever leading an ambush. The other currents accept him at the table for that reason: he does not ask for command of the fighters.\n\nHe chairs the Shura-ye-Sangsar, the council that holds treasury, armed force, propaganda and logistics together. Anyone who ignores the council, on paper at least, loses Abdul Rahman’s money and Hamidullah Safi’s recruits. He does not issue fire orders to Omar Hakimi. His work is to keep five currents as one organisation.',
    personality: 'He is slow, formal and vain in a clerical way. He speaks little, corrects others and does not raise his voice. Foreigners are not a target to hit: they are a problem to keep out of the court. Sokolov is not to set foot there. He fears a wrong ruling more than an airstrike, because a wrong ruling costs him the village elders.',
    appearanceItems: [
      'Moves little from the court compound',
      'Does not carry long weapons',
      'Light guard at the gate',
      'Does not use a satellite phone',
      'Handwritten rulings posted in the courtyard',
    ],
    networkSteps: [
      'Occupied district court — south-west Kandahar city',
      'Courtyard, hearing room, civilian roof antenna',
      'Messengers, not radio',
      'Intelligence reports through Rahmatullah Hotak',
    ],
    networkNote: 'The civilian antenna is for short links only, not Faisal’s radio net. Rahman is received now and then, Hakimi almost never. Faisal Noor does not enter: his radio voice is already too exposed.',
    relationshipItems: [
      'Rahmatullah Hotak — gathers information for him. In return he gets the council’s protection.',
      'Abdul Rahman — brings ushr money. Samiullah gives the treasury religious recognition.',
      'Omar Hakimi — commands the fighters. The judge covers operations; he does not command fire.',
      'Faisal Noor — reads courtyard rulings on the radio. Samiullah finds him vulgar, but radio travels farther than a wall.',
      'Hamidullah Safi — blessed in public: recruits arrive with the council’s recognition.',
    ],
    weakness: 'He does not plan ambushes. If he stays in place the network stays united. If he is gone, the currents split.',
    treeLinkSteps: [
      'Shura-ye-Sangsar',
      'Samiullah Barakzai',
      'Religious cover',
      'Five currents held together',
    ],
    treeLinkNote: 'Without Samiullah the five currents remain five trades standing side by side. He is not a military commander, but he holds the organisation together politically.',
  },
  rahmatullahHotak: {
    label: 'Karg',
    title: 'Rahmatullah Hotak — "Karg"',
    meta: meta(metaEn, {
      name: 'Rahmatullah Hotak',
      nickname: '"Karg" — The Crow',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Arghandab District, Kandahar',
      faction: 'Taliban — Shura-ye-Sangsar / Daftar-e-Khabar',
      role: 'Intelligence chief',
      category: 'Intelligence',
      association: 'Handler for Farid Ahmad Khan',
    }),
    sections: sectionsEn,
    profile: 'Hotak grew up in Arghandab as a courier and then an informant. He has never led an armed cell. Shepherds call him Karg because they see him on the ridges and then he is gone.\n\nHe runs the council’s intelligence service. He is the only Taliban authorised to handle Farid Ahmad Khan: not as a friend, as a source. What Farid sells becomes warnings for Omar Hakimi and route advice for Bashir Achakzai.',
    personality: 'He is taciturn, suspicious, almost superstitious. He counts things. He does not raise his voice and does not make speeches. He cannot stand noise, Faisal first of all. The relationship with Farid is dirty: he pays him, blackmails him, does not respect him.',
    appearanceItems: [
      'Pakol cap, not a turban',
      'Binoculars, notebook, weak repeater',
      'Avoids the main road',
      'Repeater off in suspicious coincidence with Farid’s shifts',
    ],
    networkSteps: [
      'Observation post “Crest Karg”',
      'Hills north-west of Arghandab',
      'Stone shelter, tarp, low repeater',
      'City cut-out: a used-phone seller',
    ],
    networkNote: 'He meets Farid only through the intermediary. The two are never in the same room. He sleeps in the valley, in a safe house, not on the observation post.',
    relationshipItems: [
      'Samiullah Barakzai — his only superior. Hotak brings him selected news.',
      'Farid Ahmad Khan — most useful and dirtiest source. A surveillance photograph used as leverage.',
      'Omar Hakimi — receives cleaned warnings, often without knowing where they come from.',
      'Bashir Achakzai — buys checkpoint advice; in return he passes truck movements.',
    ],
    weakness: 'An information threat, not a fire threat. Without him fighters stay armed but lose early warning.',
    treeLinkSteps: [
      'Farid Ahmad Khan',
      'Rahmatullah Hotak',
      'Council',
      'Warnings to Hakimi and Bashir',
    ],
    treeLinkNote: 'He is the bridge between Farid Khan and the Taliban. Without him the mole has no useful recipient, and the council loses its information.',
  },
  hamidullahSafi: {
    label: 'Ustad',
    title: 'Hamidullah Safi — "Ustad"',
    meta: meta(metaEn, {
      name: 'Hamidullah Safi',
      nickname: '“Ustad”, among the boys',
      age: '29',
      nationality: 'Afghan',
      origin: 'Khakrez District, Kandahar',
      faction: 'Taliban — Sada-ye-Maiwand',
      role: 'Recruiter',
      category: 'Recruitment',
      association: 'Village madrasa',
    }),
    sections: sectionsEn,
    profile: 'Safi is twenty-nine and has a courtyard voice. Son of a village imam in Khakrez, he learned to talk to boys before he learned to shoot. He is not a propagandist: he does not sit at the microphone. He is not a commander: he does not keep a cell. He walks boys to the gate and then lets them go.\n\nHe finds, persuades, moves. He works with family debt, revenge, hunger and pride. Rahman pays the families. He refused to become Faisal’s second voice, because radio would burn him.',
    personality: 'He is charismatic in a young way, not theatrical like Faisal. He believes what he says more than Rahman and less than Samiullah. He bristles if he is called a soldier. He fears Hotak, because a list of names in intelligence hands is a death sentence.',
    appearanceItems: [
      'Young, black beard',
      'Black waistcoat over white kameez',
      'No turban',
      'No long weapons on site',
      'White van with a repaired bumper',
    ],
    networkSteps: [
      'Madrasa “Safi’s Courtyard” — north of Kandahar, Khakrez',
      'One-storey building, tree, compound wall',
      'Lessons in the courtyard, departures when the village is quiet',
      'Weapons only later, from the lashkar',
    ],
    networkNote: 'It is not a training camp. He avoids Gereshk and Helmand, because there the boys end up in Rahman’s fields instead of the cells.',
    relationshipItems: [
      'Faisal Noor — current-mate, not boss. Radio prepares; the courtyard collects.',
      'Omar Hakimi — where the boys end up. In return Safi keeps them out of the fields.',
      'Abdul Rahman — pays the families. Safi hates that the money comes from opium, but he takes it.',
      'Samiullah Barakzai — blesses him in public and finds him too heated in private.',
    ],
    weakness: 'A threat of new men, not of fire. If the madrasa closes, the flow toward Hakimi stops.',
    treeLinkSteps: [
      'Sada-ye-Maiwand',
      'Hamidullah Safi',
      'Courtyard / madrasa',
      'Recruits toward Hakimi',
    ],
    treeLinkNote: 'Without Safi, Hakimi burns through villages and Faisal talks to a network that does not renew itself.',
  },
  zahirPopalzai: {
    label: 'Shisha',
    title: 'Zahir Popalzai — "Shisha"',
    meta: meta(metaEn, {
      name: 'Zahir Popalzai',
      nickname: '"Shisha"',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'North of Lashkar Gah, Helmand',
      faction: 'Taliban — Bayt al-Mal-e-Helmand',
      role: 'Clandestine laboratory supervisor',
      category: 'Treasury / processing',
      association: 'Laboratory, not cultivation',
    }),
    sections: sectionsEn,
    profile: 'Zahir is not an opium lord. He is a former chemistry teacher from Lashkar Gah. Rahman took him because he can weigh, not because he can shoot. The nickname Shisha comes from the laboratory glass.\n\nHe is the only person responsible for processing in Rahman’s network. He receives opium paste and returns a finished product. He does not command the fields and does not take loads to the border.',
    personality: 'He is anxious and educated. He is not an ideologue. He fears Rahman more than the coalition. He smokes constantly, yellow fingers. Samiullah considers him impure: both Rahman and the judge want that distance.',
    appearanceItems: [
      'Prayer cap, no turban',
      'Nicotine-yellow fingers',
      'Rarely goes out',
      'School notebooks for the weights',
    ],
    networkSteps: [
      'Laboratory “House Shisha” — north of Lashkar Gah',
      'Walled house between fields and a canal',
      'Plastic sheeting, drums, generator, drain pit',
      'Two helpers, unarmed',
    ],
    networkNote: 'Rahman does not enter: he sends a cousin to collect. Hakimi does not know exactly where it is. The laboratory and the fields are two different things.',
    relationshipItems: [
      'Abdul Rahman — his master. Zahir owes him a house and money; Rahman owes him the extra profit the fields cannot make alone.',
      'Bashir Achakzai — brought solvent and asked too many questions. Containers now arrive as warehouse goods.',
      'Samiullah Barakzai — will not receive him. In public the treasury stays acceptable because the lab stays invisible.',
    ],
    weakness: 'An indirect threat, through money. A strike on the laboratory cuts Rahman’s profit and delays wages.',
    treeLinkSteps: [
      'Rahman’s fields',
      'Zahir Popalzai',
      'Laboratory',
      'Money for Hakimi, Faisal, Safi',
    ],
    treeLinkNote: 'Without him the treasury sells raw opium paste, with less profit and more people in the middle.',
  },
  nazarMohammadAlizai: {
    label: 'Tufan',
    title: 'Nazar Mohammad Alizai — "Tufan"',
    meta: meta(metaEn, {
      name: 'Nazar Mohammad Alizai',
      nickname: '"Tufan" — Storm',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Dand District, Kandahar',
      faction: 'Taliban — Lashkar-e-Maiwand',
      role: 'Air-defence lead',
      category: 'Tactical air defence',
      association: 'AAA battery / MANPADS',
    }),
    sections: sectionsEn,
    profile: 'Alizai spent years as a gunner on open vehicles. A helicopter killed his brother; since then the sky has been his work. Hakimi pulled him off ambushes because on the ground he wasted ammunition and against aircraft he used it well.\n\nHe is the lashkar’s only referent for the low-level air threat. Towed guns, heavy machine guns and a few shoulder-fired missiles that arrived — without him knowing for certain — from Sokolov’s network through Hakimi.',
    personality: 'He is stubborn, bitter and simple. He treats the sky as a personal enemy. He respects Hakimi because Hakimi gave him the missiles. He envies Faisal, whose voice travels far without being shot at. He chews naswar. He prays looking up.',
    appearanceItems: [
      'No turban',
      'Camouflage jacket over the kameez',
      'Narrow gaze, often against the light',
      'Moves the pieces in a short radius around the ridge',
    ],
    networkSteps: [
      'Battery “Crest Tufan” — south of Kandahar',
      'Towed pieces, sandbags, tarps',
      'Vehicle with a machine gun',
      'Missile hides and dummy pieces',
    ],
    networkNote: 'He uses observers in the valley, not Hotak’s: they cover the same ground and avoid each other. He sleeps in a mid-slope quarry.',
    relationshipItems: [
      'Omar Hakimi — gave him this trade and the missiles. Without Tufan, Hakimi moves men visible from above.',
      'Viktor Sokolov — has never met him. The missiles arrive as “the brothers’ stuff”.',
      'Bashir Achakzai — trucks raise dust and ruin the view. A trade conflict, not a council feud.',
    ],
    weakness: 'A direct air threat: AAA and MANPADS. No political weight. Without the battery, the court, the towers and the safe houses sit more exposed.',
    treeLinkSteps: [
      'Lashkar-e-Maiwand',
      'Nazar Mohammad Alizai',
      'Crest Tufan',
      'Low flight over Kandahar made costly',
    ],
    treeLinkNote: 'His work makes it expensive to fly low over Kandahar, Faisal’s towers and Samiullah’s court.',
  },
  izatullahNoorzai: {
    label: 'Khatar',
    title: 'Izatullah Noorzai — "Khatar"',
    meta: meta(metaEn, {
      name: 'Izatullah Noorzai',
      nickname: '"Khatar"',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Gereshk District, Helmand',
      faction: 'Taliban — Lashkar-e-Maiwand',
      role: 'Mines and IED lead',
      category: 'Mine warfare',
      association: 'Clandestine workshop',
    }),
    sections: sectionsEn,
    profile: 'Noorzai is a roadside mechanic. He learned to build mines after one went off under him: he is missing two fingers on his left hand. Hakimi forbade him from commanding a cell after his group blew up the wrong vehicle.\n\nHe produces charges, initiators, homemade anti-tank mines and traps. He does not decide where to strike. He gets a mark on a map from one of Hakimi’s men and prepares the piece. Fighters put devices in the ground. He builds them.',
    personality: 'He is irritable, superstitious and rude. He resents Hakimi for taking his men, but he still obeys. He cannot stand Zahir Popalzai: the laboratory smell reminds him of the wrong fumes. He does not want initiators from Sokolov’s network.',
    appearanceItems: [
      'Mutilated left hand',
      'No turban',
      'Burn scar on the neck',
      'Generator audible when running',
    ],
    networkSteps: [
      'Workshop “Farm Khatar” — west of Gereshk',
      'Shed, batteries, cable, fertiliser, generator',
      'Moved on a cargo tricycle',
      'Notes, not radio',
    ],
    networkNote: 'He avoids Bashir’s convoys when he can: a fuel seizure must not lead to the initiators. Material does not stay long: it goes out to the cells.',
    relationshipItems: [
      'Omar Hakimi — his superior. Took his men and left him the bench, the maps and people who plant devices.',
      'Bashir Achakzai — for a fee hides a crate among spare parts, and can refuse when the risk is high.',
      'Abdul Rahman — pays Hakimi, Hakimi pays Khatar. Izatullah does not want opium near the fertiliser.',
    ],
    weakness: 'Dangerous to low helicopters and anyone moving on the ground. Dangerous from the air, on his own, little. Hakimi can replace him, but not quickly.',
    treeLinkSteps: [
      'Lashkar-e-Maiwand',
      'Izatullah Noorzai',
      'IED workshop',
      'Tracks made dangerous without an ambush',
    ],
    treeLinkNote: 'Important on the ground, irrelevant in politics. If he is gone, the lashkar loses the man who makes roads dangerous even where there is no ambush.',
  },
  bashirAchakzai: {
    label: 'Karwan',
    title: 'Bashir Achakzai — "Karwan"',
    meta: meta(metaEn, {
      name: 'Bashir Achakzai',
      nickname: '"Karwan" — The Caravan',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Achakzai belt of Spin Boldak, Kandahar',
      faction: 'Taliban — Karwan-e-Dasht',
      role: 'Convoy lead',
      category: 'Logistics',
      association: 'Fuel, food, spares — not opium, not Sokolov’s weapons',
    }),
    sections: sectionsEn,
    profile: 'Bashir is a merchant before he is a Taliban. The Achakzai hold the roads. He holds the trucks. Rahman took him because his drivers do not ask questions. Hakimi uses him because a cell without fuel is a cell on foot.\n\nHe organises convoys on the main highway and the parallel tracks: fuel, flour, spares, generators, sometimes cash. Rahman forbade him from loading opium paste. Hakimi forbade Sokolov’s crates when the seizure risk is high.',
    personality: 'He is calculating, cordial, visibly greedy, with a market smile. He does not preach. Samiullah tolerates him. Faisal ignores him. Hakimi treats him as a supplier. Rahman treats him as an employee who thinks he is a partner.',
    appearanceItems: [
      'Embroidered waistcoat',
      'Gold ring',
      'Trimmed beard',
      'Does not show a rifle',
      'Afghan drivers, mixed plates, dirty tarps',
    ],
    networkSteps: [
      'Warehouse “Karwan Compound” — main road east of Gereshk',
      'Sheds, trucks, tanks, a minimal workshop',
      'Short convoys, three to six vehicles',
      'Civilian radio, not Faisal’s',
    ],
    networkNote: 'He stands in the compound like a firm owner and keeps a house in the Gereshk bazaar. His men know what they must not load.',
    relationshipItems: [
      'Abdul Rahman — buys food and jerrycans, and the right not to touch opium.',
      'Omar Hakimi — buys the fuel that keeps the cells moving.',
      'Rahmatullah Hotak — sells checkpoint advice and buys truck movements.',
      'Latif Ishaqzai — gets spares and light loads when the highway is too watched.',
      'Haji Khairullah Barech — swaps loads at the crossing: Iranian fuel for food, people for commissions.',
      'Izatullah Noorzai — sometimes a ride for initiators, paid and uninspected.',
    ],
    weakness: 'A logistics threat. A strike on the warehouse stops the rhythm. A strike on one truck stops one trip.',
    treeLinkSteps: [
      'Karwan-e-Dasht',
      'Bashir Achakzai',
      'Convoys',
      'Hakimi on foot / Rahman without food, if he falls',
    ],
    treeLinkNote: 'Without him the other currents stay locked in their own districts. High importance: the network becomes slow and local.',
  },
  latifIshaqzai: {
    label: 'Pista',
    title: 'Latif Ishaqzai — "Pista"',
    meta: meta(metaEn, {
      name: 'Latif Ishaqzai',
      nickname: '"Pista"',
      age: 'Unconfirmed',
      nationality: 'Afghan',
      origin: 'Dishu District, Dasht-e Margo',
      faction: 'Taliban — Karwan-e-Dasht',
      role: 'Improvised airstrip manager',
      category: 'Improvised air logistics',
      association: 'Dirt strip in the desert',
    }),
    sections: sectionsEn,
    profile: 'Latif has spent his life reading the desert: soil, wind, salt. He is not a pilot and not an opium trafficker. He says where a landing is possible and lights two fires.\n\nHe runs the dirt strip in the Dasht-e Margo. Loads are light: spares, cash, people, sometimes a technician. Sokolov has asked to use it. Latif reported that to Bashir, and Bashir has not said yes yet.',
    personality: 'He is solitary, dry, little interested in the council. He talks about wind the way Tufan talks about the sky, but horizontally. He keeps Rahman away, because opium draws eyes into the desert. He respects Barech, because the crossing is a similar trade.',
    appearanceItems: [
      'Light keffiyeh',
      'Wind-burned face',
      'No turban',
      'One vehicle with jerrycans',
      'No fixed generators',
    ],
    networkSteps: [
      'Dirt strip “Pista Latif” — Dasht-e Margo',
      'Packed earth, two drums as a threshold',
      'Tent and vehicle far off, no buildings',
      'Fires only if the aircraft is coming',
    ],
    networkNote: 'No long radio: a short transceiver. Afterward he covers the ruts. If used, it shows. If left alone, the wind covers it.',
    relationshipItems: [
      'Bashir Achakzai — his superior. The highway moves weight; the strip moves urgency.',
      'Haji Khairullah Barech — the other western gate, almost a polite rival. When Zaranj gets dirty, someone tries to dump on the strip.',
      'Omar Hakimi — passed Sokolov’s request to Bashir. Latif does not want a weapons aircraft on his strip.',
    ],
    weakness: 'It resupplies and makes people disappear. For aircrew it is little danger unless missiles that are not his appear on the strip.',
    treeLinkSteps: [
      'Karwan-e-Dasht',
      'Latif Ishaqzai',
      'Desert strip',
      'The network’s only air door',
    ],
    treeLinkNote: 'Medium now, high if Sokolov gets use of it. Without Latif the strip is still there, but nobody marks it at the right moment.',
  },
  hajiKhairullahBarech: {
    label: 'Haji',
    title: 'Haji Khairullah Barech',
    meta: meta(metaEn, {
      name: 'Khairullah Barech',
      nickname: '“Haji”, at the crossing',
      age: 'Unconfirmed',
      nationality: 'Afghan — Barech tribe, Nimruz',
      origin: 'Zaranj and lower Helmand',
      faction: 'Taliban — Karwan-e-Dasht',
      role: 'Border smuggling',
      category: 'Crossing / de facto customs',
      association: 'People, Iranian fuel, cash — not opium, not weapons',
    }),
    sections: sectionsEn,
    profile: 'Haji Khairullah is a border man. The Barech hold water, tracks and relatives across the line. He is not a Kandahar Taliban: he is a Nimruz Taliban who accepts the flag because the flag leaves him the river.\n\nHe controls a compound on the crossing and a seasonal ford. He moves people, Iranian fuel drums, civilian spare parts, cash. He does not move Sokolov’s crates or Zahir’s loads. Rahman tried to buy his opium channels: he said no.',
    personality: 'He is impassive, slow, calmly insulting. He measures men by debt. He does not believe Faisal’s sermons, too far away, and he does not fear Hakimi, too far away. He fears drones and floods. He will not host Sokolov: a Russian at the crossing is an ending.',
    appearanceItems: [
      'Bulky dark turban',
      'Heavy shawl',
      'Salt-and-pepper beard',
      'Low, steady gaze',
      'Moves little; his sons run as couriers',
    ],
    networkSteps: [
      'Compound “Haji Crossing” — north-east of Zaranj',
      'Two low warehouses, a scale, vehicles',
      'Seasonal ford toward the water',
      'Civilian radio, no towers, no air defence',
    ],
    networkNote: 'He pays every side. He holds hostages for debt, not prisoners of war. Closing the compound closes the western door.',
    relationshipItems: [
      'Bashir Achakzai — counterpart, not boss. Iranian fuel for flour and spares; the crossing fills, the road distributes.',
      'Abdul Rahman — offered opium and was told no. Not an enemy’s no: a customs man’s no.',
      'Latif Ishaqzai — the other door. Haji pushes, Latif resists, Bashir decides.',
      'Samiullah Barakzai — recognised him without summoning him. That recognition stops Hakimi from “putting order” on the river.',
    ],
    weakness: 'A resupply, people-movement and cash-movement threat. Little danger in a fight. If he falls, Bashir overloads the highway.',
    treeLinkSteps: [
      'Karwan-e-Dasht',
      'Haji Khairullah Barech',
      'Zaranj crossing',
      'The network’s western door',
    ],
    treeLinkNote: 'The refusal of opium and weapons is not ideology. It is how he keeps the door open.',
  },
  afghanistanChart: {
    label: 'Afghanistan',
    title: 'Operational chart — Afghanistan',
    body: 'Theatre operational map. No strings on the chart: geographic reference for Kandahar, Helmand, Hwy 1, Dasht-e Margo and Zaranj.',
  },
};
