import samiullahBarakzaiImg from '../../img/characters/SamiullahBarakzai.png';
import rahmatullahHotakImg from '../../img/characters/RahmatullahHotak.png';
import hamidullahSafiImg from '../../img/characters/HamidullahSafi.png';
import zahirPopalzaiImg from '../../img/characters/ZahirPopalzai.png';
import nazarMohammadAlizaiImg from '../../img/characters/NazarMohammadAlizai.png';
import izatullahNoorzaiImg from '../../img/characters/IzatullahNoorzai.png';
import bashirAchakzaiImg from '../../img/characters/BashirAchakzai.png';
import latifIshaqzaiImg from '../../img/characters/LatifIshaqzai.png';
import hajiKhairullahBarechImg from '../../img/characters/HajiKhairullahBarech.png';
import abdulRahmanImg from '../../img/characters/AbdulRahman.png';
import omarHakimiImg from '../../img/characters/OmarHakimi.png';
import faisalNoorImg from '../../img/characters/FaisalNoor.png';
import viktorSokolovImg from '../../img/characters/ViktorSokolov.png';
import faridAhmadKhanImg from '../../img/characters/FaridKhan.png';
import afghanistanChartImg from '../../img/lidc/chart.png';

const PHOTO_WIDTH = 10.4;
const DOSSIER = ['profile', 'personality', 'appearance', 'network', 'relationships', 'weakness', 'treeLink'];

export const LIDC_STORYLINE_WHITEBOARD_ITEMS = [
  {
    id: 'samiullahBarakzai',
    type: 'character',
    image: samiullahBarakzaiImg,
    labelKey: 'lidc.storyline.whiteboardItems.samiullahBarakzai.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.samiullahBarakzai.title',
    dossierSections: DOSSIER,
    x: 48,
    y: 17.2,
    width: PHOTO_WIDTH,
    rotation: -0.7,
  },
  {
    id: 'faisalNoor',
    type: 'character',
    image: faisalNoorImg,
    labelKey: 'lidc.storyline.whiteboardItems.faisalNoor.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.faisalNoor.title',
    dossierSections: DOSSIER,
    x: 36.3,
    y: 14.8,
    width: PHOTO_WIDTH,
    rotation: -1.1,
  },
  {
    id: 'omarHakimi',
    type: 'character',
    image: omarHakimiImg,
    labelKey: 'lidc.storyline.whiteboardItems.omarHakimi.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.omarHakimi.title',
    dossierSections: DOSSIER,
    x: 58.2,
    y: 26.9,
    width: PHOTO_WIDTH,
    rotation: 0.5,
  },
  {
    id: 'nazarMohammadAlizai',
    type: 'character',
    image: nazarMohammadAlizaiImg,
    labelKey: 'lidc.storyline.whiteboardItems.nazarMohammadAlizai.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.nazarMohammadAlizai.title',
    dossierSections: DOSSIER,
    x: 58.3,
    y: 43.5,
    width: PHOTO_WIDTH,
    rotation: 0.9,
  },
  {
    id: 'viktorSokolov',
    type: 'character',
    image: viktorSokolovImg,
    labelKey: 'lidc.storyline.whiteboardItems.viktorSokolov.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.viktorSokolov.title',
    dossierSections: DOSSIER,
    x: 65.5,
    y: 37,
    width: PHOTO_WIDTH,
    rotation: -0.8,
  },
  {
    id: 'rahmatullahHotak',
    type: 'character',
    image: rahmatullahHotakImg,
    labelKey: 'lidc.storyline.whiteboardItems.rahmatullahHotak.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.rahmatullahHotak.title',
    dossierSections: DOSSIER,
    x: 38.4,
    y: 34.4,
    width: PHOTO_WIDTH,
    rotation: 0.6,
  },
  {
    id: 'hamidullahSafi',
    type: 'character',
    image: hamidullahSafiImg,
    labelKey: 'lidc.storyline.whiteboardItems.hamidullahSafi.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.hamidullahSafi.title',
    dossierSections: DOSSIER,
    x: 30.8,
    y: 27.9,
    width: PHOTO_WIDTH,
    rotation: -0.4,
  },
  {
    id: 'afghanistanChart',
    type: 'map',
    image: afghanistanChartImg,
    labelKey: 'lidc.storyline.whiteboardItems.afghanistanChart.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.afghanistanChart.title',
    x: 43.4,
    y: 40.3,
    width: 16.8,
    rotation: -0.5,
  },
  {
    id: 'faridAhmadKhan',
    type: 'character',
    image: faridAhmadKhanImg,
    labelKey: 'lidc.storyline.whiteboardItems.faridAhmadKhan.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.faridAhmadKhan.title',
    dossierSections: DOSSIER,
    x: 31.4,
    y: 40.3,
    width: PHOTO_WIDTH,
    rotation: 0.7,
  },
  {
    id: 'izatullahNoorzai',
    type: 'character',
    image: izatullahNoorzaiImg,
    labelKey: 'lidc.storyline.whiteboardItems.izatullahNoorzai.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.izatullahNoorzai.title',
    dossierSections: DOSSIER,
    x: 59.8,
    y: 58.8,
    width: PHOTO_WIDTH,
    rotation: -0.9,
  },
  {
    id: 'zahirPopalzai',
    type: 'character',
    image: zahirPopalzaiImg,
    labelKey: 'lidc.storyline.whiteboardItems.zahirPopalzai.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.zahirPopalzai.title',
    dossierSections: DOSSIER,
    x: 52.7,
    y: 58.3,
    width: PHOTO_WIDTH,
    rotation: -0.5,
  },
  {
    id: 'bashirAchakzai',
    type: 'character',
    image: bashirAchakzaiImg,
    labelKey: 'lidc.storyline.whiteboardItems.bashirAchakzai.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.bashirAchakzai.title',
    dossierSections: DOSSIER,
    x: 39,
    y: 52.1,
    width: PHOTO_WIDTH,
    rotation: 0.4,
  },
  {
    id: 'latifIshaqzai',
    type: 'character',
    image: latifIshaqzaiImg,
    labelKey: 'lidc.storyline.whiteboardItems.latifIshaqzai.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.latifIshaqzai.title',
    dossierSections: DOSSIER,
    x: 33.3,
    y: 61,
    width: PHOTO_WIDTH,
    rotation: -0.7,
  },
  {
    id: 'hajiKhairullahBarech',
    type: 'character',
    image: hajiKhairullahBarechImg,
    labelKey: 'lidc.storyline.whiteboardItems.hajiKhairullahBarech.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.hajiKhairullahBarech.title',
    dossierSections: DOSSIER,
    x: 40.9,
    y: 67.5,
    width: PHOTO_WIDTH,
    rotation: 0.8,
  },
  {
    id: 'abdulRahman',
    type: 'character',
    image: abdulRahmanImg,
    labelKey: 'lidc.storyline.whiteboardItems.abdulRahman.label',
    detailTitleKey: 'lidc.storyline.whiteboardItems.abdulRahman.title',
    dossierSections: DOSSIER,
    x: 51.3,
    y: 37.9,
    width: PHOTO_WIDTH,
    rotation: -0.6,
  },
];

const pinTop = { x: 0.5, y: 0.09 };

export const LIDC_STORYLINE_WHITEBOARD_CONNECTIONS = [
  {
    id: 'samiullah-faisal',
    from: 'samiullahBarakzai',
    to: 'faisalNoor',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'samiullah-hakimi',
    from: 'samiullahBarakzai',
    to: 'omarHakimi',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'samiullah-rahman',
    from: 'samiullahBarakzai',
    to: 'abdulRahman',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'samiullah-hotak',
    from: 'samiullahBarakzai',
    to: 'rahmatullahHotak',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'samiullah-safi',
    from: 'samiullahBarakzai',
    to: 'hamidullahSafi',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'faisal-safi',
    from: 'faisalNoor',
    to: 'hamidullahSafi',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'hotak-farid',
    from: 'rahmatullahHotak',
    to: 'faridAhmadKhan',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'hotak-bashir',
    from: 'rahmatullahHotak',
    to: 'bashirAchakzai',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'rahman-zahir',
    from: 'abdulRahman',
    to: 'zahirPopalzai',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'zahir-bashir',
    from: 'zahirPopalzai',
    to: 'bashirAchakzai',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'hakimi-tufan',
    from: 'omarHakimi',
    to: 'nazarMohammadAlizai',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'sokolov-hakimi',
    from: 'viktorSokolov',
    to: 'omarHakimi',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'tufan-khatar',
    from: 'nazarMohammadAlizai',
    to: 'izatullahNoorzai',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'bashir-latif',
    from: 'bashirAchakzai',
    to: 'latifIshaqzai',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
  {
    id: 'latif-barech',
    from: 'latifIshaqzai',
    to: 'hajiKhairullahBarech',
    fromAnchor: pinTop,
    toAnchor: pinTop,
  },
];
