/**
 * Airport Configuration
 * Add new airports here to make them visible in the system
 *
 * isHeliport: true if this is a heliport/FOB (only helicopters can land)
 * isCarrier: true if this is a carrier (naval aviation base)
 * herculesBase: true if C-130 Hercules can spawn/operate from this base
 */
export const airports = [
  // ==== MAIN BASE ====
  {
    id: 'aleppo',
    name: 'Aleppo',
    displayName: 'Aleppo International',
    icao: 'OSAP',
    isMainBase: true,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Aleppo',
    coordinates: { lat: 36.180833, lon: 37.224444 },
  },

  // ==== THEATER AIRPORTS ====
  {
    id: 'hama',
    name: 'Hama',
    displayName: 'Hama',
    icao: 'OS58',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Hama',
    coordinates: { lat: 35.122655, lon: 36.722176 },
  },
  {
    id: 'deir-ez-zor',
    name: 'Deir ez Zor',
    displayName: 'Deir ez Zor',
    icao: 'OSDZ',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Deir_ez_Zor',
    coordinates: { lat: 35.295367, lon: 40.173177 },
  },
  {
    id: 'rene-mouawad',
    name: 'Rene Mouawad',
    displayName: 'Rene Mouawad',
    icao: 'OLKA',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Rene_Mouawad',
    coordinates: { lat: 34.58933, lon: 36.022315 },
  },
  {
    id: 'al-qusayr',
    name: 'Al Qusayr',
    displayName: 'Al Qusayr',
    icao: 'OS70',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Al_Qusayr',
    coordinates: { lat: 34.568682, lon: 36.563393 },
  },
  {
    id: 'tiyas',
    name: 'Tiyas',
    displayName: 'Tiyas',
    icao: 'OS72',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Tiyas',
    coordinates: { lat: 34.527303, lon: 37.633076 },
  },
  
  {
    id: 'palmyra',
    name: 'Palmyra',
    displayName: 'Palmyra',
    icao: 'OSPR',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Palmyra',
    coordinates: { lat: 34.563906, lon: 38.307199 },
  },
  {
    id: 'shayrat',
    name: 'Shayrat',
    displayName: 'Shayrat',
    icao: 'OS65',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Shayrat',
    coordinates: { lat: 34.492867, lon: 36.914471 },
  },
  {
    id: 'wujah-al-hajar',
    name: 'Wujah Al Hajar',
    displayName: 'Wujah Al Hajar',
    icao: 'Z19O',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Wujah_Al_Hajar',
    coordinates: { lat: 34.275138, lon: 35.69009 },
  },
  {
    id: 'an-nasiriyah',
    name: 'An Nasiriyah',
    displayName: 'An Nasiriyah',
    icao: 'OS64',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'An_Nasiriyah',
    coordinates: { lat: 33.920519, lon: 36.868019 },
  },
  {
    id: 'sayqal',
    name: 'Sayqal',
    displayName: 'Sayqal',
    icao: 'OS68',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Sayqal',
    coordinates: { lat: 33.68075, lon: 37.218562 },
  },
  {
    id: 'at-tanf',
    name: 'At Tanf',
    displayName: 'At Tanf',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'At_Tanf',
    coordinates: { lat: 33.506082, lon: 38.624984 },
  },
  {
    id: 'beirut-rafic-hariri',
    name: 'Beirut Rafic Hariri',
    displayName: 'Beirut Rafic Hariri',
    icao: 'OLBA',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Beirut_Rafic_Hariri',
    coordinates: { lat: 33.850118, lon: 35.530245 },
  },
  {
    id: 'rayak',
    name: 'Rayak',
    displayName: 'Rayak',
    icao: 'OLRA',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Rayak',
    coordinates: { lat: 33.851178, lon: 35.988426 },
  },
  {
    id: 'al-dumayr',
    name: 'Al Dumayr',
    displayName: 'Al Dumayr',
    icao: 'OS61',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Al_Dumayr',
    coordinates: { lat: 33.610432, lon: 36.749977 },
  },
  {
    id: 'mezzeh',
    name: 'Mezzeh',
    displayName: 'Mezzeh',
    icao: 'OS67',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Mezzeh',
    coordinates: { lat: 33.475672, lon: 36.307527 },
  },
  {
    id: 'damascus',
    name: 'Damascus',
    displayName: 'Damascus',
    icao: 'OSDI',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Damascus',
    coordinates: { lat: 33.465747, lon: 36.503406 },
  },
  {
    id: 'h4',
    name: 'H4',
    displayName: 'H4',
    icao: 'OJHR',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'H4',
    coordinates: { lat: 32.541691, lon: 38.194947 },
  },
  {
    id: 'kiryat-shmona',
    name: 'Kiryat Shmona',
    displayName: 'Kiryat Shmona',
    icao: 'LLKS',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Kiryat_Shmona',
    coordinates: { lat: 33.213373, lon: 35.589903 },
  },
  {
    id: 'marj-ruhayyil',
    name: 'Marj Ruhayyil',
    displayName: 'Marj Ruhayyil',
    icao: 'OS63',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Marj_Ruhayyil',
    coordinates: { lat: 33.288127, lon: 36.45162 },
  },
  {
    id: 'khalkhalah',
    name: 'Khalkhalah',
    displayName: 'Khalkhalah',
    icao: 'OS69',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Khalkhalah',
    coordinates: { lat: 33.076368, lon: 36.540003 },
  },
  {
    id: 'rosh-pina',
    name: 'Rosh Pina',
    displayName: 'Rosh Pina',
    icao: 'LLIB',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Rosh_Pina',
    coordinates: { lat: 32.976718, lon: 35.553508 },
  },
  {
    id: 'tha-lah',
    name: 'Tha lah',
    displayName: 'Tha lah',
    icao: 'OS0D',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Tha_lah',
    coordinates: { lat: 32.706404, lon: 36.403529 },
  },
  {
    id: 'prince-hassan',
    name: 'Prince Hassan',
    displayName: 'Prince Hassan',
    icao: 'OJHF',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Prince_Hassan',
    coordinates: { lat: 32.165943, lon: 37.141848 },
  },
  {
    id: 'ramat-david',
    name: 'Ramat David',
    displayName: 'Ramat David',
    icao: 'LLRD',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Ramat_David',
    coordinates: { lat: 32.641654, lon: 35.209638 },
  },
  {
    id: 'king-hussein-air-college',
    name: 'King Hussein Air College',
    displayName: 'King Hussein Air College',
    icao: 'OJMF',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'King_Hussein_Air_College',
    coordinates: { lat: 32.352417, lon: 36.257367 },
  },
  {
    id: 'muwaffaq-salti',
    name: 'Muwaffaq Salti',
    displayName: 'Muwaffaq Salti',
    icao: 'OJMS',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Muwaffaq_Salti',
    coordinates: { lat: 31.824266, lon: 36.797421 },
  },
  {
    id: 'eyn-shemer',
    name: 'Eyn Shemer',
    displayName: 'Eyn Shemer',
    icao: 'LLES',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Eyn_Shemer',
    coordinates: { lat: 32.453983, lon: 34.999371 },
  },
  {
    id: 'marka',
    name: 'Marka',
    displayName: 'Marka',
    icao: 'OJAM',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Marka',
    coordinates: { lat: 31.969996, lon: 35.950959 },
  },

  // ==== CARRIERS ====
  {
    id: 'carrier-1',
    name: 'carrier_group',
    displayName: 'Carrier Group',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    isCarrier: true,
    herculesBase: false,
    csvPrefix: 'CARRIER',
    coordinates: { lat: 36.4475, lon: 34.6219 },
  },
];

/**
 * Get airport by ID
 */
export function getAirportById(id) {
  return airports.find(airport => airport.id === id);
}

/**
 * Get main base airport
 */
export function getMainBase() {
  return airports.find(airport => airport.isMainBase);
}

export default airports;
