/**
 * Airport Configuration
 * Add new airports here to make them visible in the system
 *
 * isHeliport: true if this is a heliport/FOB (only helicopters can land)
 * isCarrier: true if this is a carrier (naval aviation base)
 * herculesBase: true if C-130 Hercules can spawn/operate from this base
 */
export const airports = [
  {
    id: 'aleppo',
    name: 'Aleppo',
    displayName: 'Aleppo International',
    icao: 'OSAP',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Aleppo',
    coordinates: { lat: 36.179024, lon: 37.238350 },
  },
  {
    id: 'hama',
    name: 'Hama',
    displayName: 'Hama',
    icao: 'OS58',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Hama',
    coordinates: { lat: 35.116099, lon: 36.725473 },
  },
  {
    id: 'deir-ez-zor',
    name: 'Deir ez Zor',
    displayName: 'Deir ez Zor',
    icao: 'OSDZ',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Deir_ez_Zor',
    coordinates: { lat: 35.290033, lon: 40.161449 },
  },
  {
    id: 'rene-mouawad',
    name: 'Rene Mouawad',
    displayName: 'Rene Mouawad',
    icao: 'OLKA',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Rene_Mouawad',
    coordinates: { lat: 34.583953, lon: 35.998687 },
  },
  {
    id: 'al-qusayr',
    name: 'Al Qusayr',
    displayName: 'Al Qusayr',
    icao: 'OS70',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Al_Qusayr',
    coordinates: { lat: 34.566877, lon: 36.585415 },
  },
  {
    id: 'tiyas',
    name: 'Tiyas',
    displayName: 'Tiyas',
    icao: 'OS72',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Tiyas',
    coordinates: { lat: 34.522531, lon: 37.645765 },
  },
  {
    id: 'palmyra',
    name: 'Palmyra',
    displayName: 'Palmyra',
    icao: 'OSPR',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Palmyra',
    coordinates: { lat: 34.558236, lon: 38.331123 },
  },
  {
    id: 'shayrat',
    name: 'Shayrat',
    displayName: 'Shayrat',
    icao: 'OS65',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Shayrat',
    coordinates: { lat: 34.494640, lon: 36.894469 },
  },
  {
    id: 'wujah-al-hajar',
    name: 'Wujah Al Hajar',
    displayName: 'Wujah Al Hajar',
    icao: 'Z19O',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Wujah_Al_Hajar',
    coordinates: { lat: 34.286961, lon: 35.683990 },
  },
  {
    id: 'an-nasiriyah',
    name: 'An Nasiriyah',
    displayName: 'An Nasiriyah',
    icao: 'OS64',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'An_Nasiriyah',
    coordinates: { lat: 33.926566, lon: 36.875345 },
  },
  {
    id: 'sayqal',
    name: 'Sayqal',
    displayName: 'Sayqal',
    icao: 'OS68',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Sayqal',
    coordinates: { lat: 33.680052, lon: 37.204069 },
  },
  {
    id: 'at-tanf',
    name: 'At Tanf',
    displayName: 'At Tanf',
    icao: '',
    isMainBase: false,
    isHeliport: true,
    herculesBase: false,
    csvPrefix: 'At_Tanf',
    coordinates: { lat: 33.506451, lon: 38.614883 },
  },
  {
    id: 'beirut-rafic-hariri',
    name: 'Beirut Rafic Hariri',
    displayName: 'Beirut Rafic Hariri',
    icao: 'OLBA',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Beirut_Rafic_Hariri',
    coordinates: { lat: 33.836465, lon: 35.487417 },
  },
  {
    id: 'rayak',
    name: 'Rayak',
    displayName: 'Rayak',
    icao: 'OLRA',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Rayak',
    coordinates: { lat: 33.842902, lon: 35.976932 },
  },
  {
    id: 'al-dumayr',
    name: 'Al Dumayr',
    displayName: 'Al Dumayr',
    icao: 'OS61',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Al_Dumayr',
    coordinates: { lat: 33.614743, lon: 36.762474 },
  },
  {
    id: 'mezzeh',
    name: 'Mezzeh',
    displayName: 'Mezzeh',
    icao: 'OS67',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Mezzeh',
    coordinates: { lat: 33.482714, lon: 36.235064 },
  },
  {
    id: 'damascus',
    name: 'Damascus',
    displayName: 'Damascus',
    icao: 'OSDI',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Damascus',
    coordinates: { lat: 33.415340, lon: 36.504255 },
  },
  {
    id: 'h4',
    name: 'H4',
    displayName: 'H4',
    icao: 'OJHR',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'H4',
    coordinates: { lat: 32.536851, lon: 38.206376 },
  },
  {
    id: 'kiryat-shmona',
    name: 'Kiryat Shmona',
    displayName: 'Kiryat Shmona',
    icao: 'LLKS',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Kiryat_Shmona',
    coordinates: { lat: 33.212372, lon: 35.592420 },
  },
  {
    id: 'marj-ruhayyil',
    name: 'Marj Ruhayyil',
    displayName: 'Marj Ruhayyil',
    icao: 'OS63',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Marj_Ruhayyil',
    coordinates: { lat: 33.284184, lon: 36.444304 },
  },
  {
    id: 'khalkhalah',
    name: 'Khalkhalah',
    displayName: 'Khalkhalah',
    icao: 'OS69',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Khalkhalah',
    coordinates: { lat: 33.088310, lon: 36.534633 },
  },
  {
    id: 'rosh-pina',
    name: 'Rosh Pina',
    displayName: 'Rosh Pina',
    icao: 'LLIB',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Rosh_Pina',
    coordinates: { lat: 32.979282, lon: 35.572651 },
  },
  {
    id: 'tha-lah',
    name: 'Tha lah',
    displayName: 'Tha lah',
    icao: 'OS0D',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Tha_lah',
    coordinates: { lat: 32.698127, lon: 36.402739 },
  },
  {
    id: 'prince-hassan',
    name: 'Prince Hassan',
    displayName: 'Prince Hassan',
    icao: 'OJHF',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Prince_Hassan',
    coordinates: { lat: 32.152161, lon: 37.160581 },
  },
  {
    id: 'ramat-david',
    name: 'Ramat David',
    displayName: 'Ramat David',
    icao: 'LLRD',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Ramat_David',
    coordinates: { lat: 32.675081, lon: 35.177260 },
  },
  {
    id: 'king-hussein-air-college',
    name: 'King Hussein Air College',
    displayName: 'King Hussein Air College',
    icao: 'OJMF',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'King_Hussein_Air_College',
    coordinates: { lat: 32.348794, lon: 36.270213 },
  },
  {
    id: 'muwaffaq-salti',
    name: 'Muwaffaq Salti',
    displayName: 'Muwaffaq Salti',
    icao: 'OJMS',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Muwaffaq_Salti',
    coordinates: { lat: 31.819166, lon: 36.790783 },
  },
  {
    id: 'eyn-shemer',
    name: 'Eyn Shemer',
    displayName: 'Eyn Shemer',
    icao: 'LLES',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Eyn_Shemer',
    coordinates: { lat: 32.439769, lon: 35.014694 },
  },
  {
    id: 'marka',
    name: 'Marka',
    displayName: 'Marka',
    icao: 'OJAM',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Marka',
    coordinates: { lat: 31.978747, lon: 36.007007 },
  },
  {
    id: 'abu-al-duhur',
    name: 'Abu al-Duhur',
    displayName: 'Abu al-Duhur',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Abu_al_Duhur',
    coordinates: { lat: 35.731462, lon: 37.118802 },
  },
  {
    id: 'adana-sakirpasa',
    name: 'Adana Sakirpasa',
    displayName: 'Adana Sakirpasa',
    icao: '',
    isMainBase: true,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Adana_Sakirpasa',
    coordinates: { lat: 36.988281, lon: 35.291372 },
  },
  {
    id: 'akrotiri',
    name: 'Akrotiri',
    displayName: 'Akrotiri',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Akrotiri',
    coordinates: { lat: 34.594066, lon: 32.974818 },
  },
  {
    id: 'bassel-al-assad',
    name: 'Bassel Al-Assad',
    displayName: 'Bassel Al-Assad',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Bassel_Al_Assad',
    coordinates: { lat: 35.411590, lon: 35.950033 },
  },
  {
    id: 'ben-gurion',
    name: 'Ben Gurion',
    displayName: 'Ben Gurion',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Ben_Gurion',
    coordinates: { lat: 32.012418, lon: 34.870943 },
  },
  {
    id: 'ercan',
    name: 'Ercan',
    displayName: 'Ercan',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Ercan',
    coordinates: { lat: 35.159250, lon: 33.490111 },
  },
  {
    id: 'gaziantep',
    name: 'Gaziantep',
    displayName: 'Gaziantep',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Gaziantep',
    coordinates: { lat: 36.951779, lon: 37.462742 },
  },
  {
    id: 'gazipasa',
    name: 'Gazipasa',
    displayName: 'Gazipasa',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Gazipasa',
    coordinates: { lat: 36.297823, lon: 32.286068 },
  },
  {
    id: 'gecitkale',
    name: 'Gecitkale',
    displayName: 'Gecitkale',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Gecitkale',
    coordinates: { lat: 35.236404, lon: 33.707278 },
  },
  {
    id: 'h3',
    name: 'H3',
    displayName: 'H3',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'H3',
    coordinates: { lat: 32.940993, lon: 39.732583 },
  },
  {
    id: 'h3-northwest',
    name: 'H3 Northwest',
    displayName: 'H3 Northwest',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'H3_Northwest',
    coordinates: { lat: 33.070356, lon: 39.606626 },
  },
  {
    id: 'h3-southwest',
    name: 'H3 Southwest',
    displayName: 'H3 Southwest',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'H3_Southwest',
    coordinates: { lat: 32.738030, lon: 39.612247 },
  },
  {
    id: 'haifa',
    name: 'Haifa',
    displayName: 'Haifa',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Haifa',
    coordinates: { lat: 32.806453, lon: 35.045021 },
  },
  {
    id: 'hatay',
    name: 'Hatay',
    displayName: 'Hatay',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Hatay',
    coordinates: { lat: 36.371270, lon: 36.298090 },
  },
  {
    id: 'hatzor',
    name: 'Hatzor',
    displayName: 'Hatzor',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Hatzor',
    coordinates: { lat: 31.766167, lon: 34.735268 },
  },
  {
    id: 'herzliya',
    name: 'Herzliya',
    displayName: 'Herzliya',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Herzliya',
    coordinates: { lat: 32.177311, lon: 34.844129 },
  },
  {
    id: 'incirlik',
    name: 'Incirlik',
    displayName: 'Incirlik',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Incirlik',
    coordinates: { lat: 36.994254, lon: 35.412713 },
  },
  {
    id: 'jirah',
    name: 'Jirah',
    displayName: 'Jirah',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Jirah',
    coordinates: { lat: 36.099410, lon: 37.920906 },
  },
  {
    id: 'king-abdullah-ii',
    name: 'King Abdullah II',
    displayName: 'King Abdullah II',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'King_Abdullah_II',
    coordinates: { lat: 31.999049, lon: 36.232154 },
  },
  {
    id: 'kingsfield',
    name: 'Kingsfield',
    displayName: 'Kingsfield',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Kingsfield',
    coordinates: { lat: 35.016621, lon: 33.721656 },
  },
  {
    id: 'kuweires',
    name: 'Kuweires',
    displayName: 'Kuweires',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Kuweires',
    coordinates: { lat: 36.189374, lon: 37.570439 },
  },
  {
    id: 'larnaca',
    name: 'Larnaca',
    displayName: 'Larnaca',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Larnaca',
    coordinates: { lat: 34.865620, lon: 33.613584 },
  },
  {
    id: 'megiddo',
    name: 'Megiddo',
    displayName: 'Megiddo',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Megiddo',
    coordinates: { lat: 32.597578, lon: 35.220203 },
  },
  {
    id: 'minakh',
    name: 'Minakh',
    displayName: 'Minakh',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Minakh',
    coordinates: { lat: 36.522812, lon: 37.033622 },
  },
  {
    id: 'nicosia',
    name: 'Nicosia',
    displayName: 'Nicosia',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Nicosia',
    coordinates: { lat: 35.143831, lon: 33.282144 },
  },
  {
    id: 'palmachim',
    name: 'Palmachim',
    displayName: 'Palmachim',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Palmachim',
    coordinates: { lat: 31.894923, lon: 34.688798 },
  },
  {
    id: 'paphos',
    name: 'Paphos',
    displayName: 'Paphos',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Paphos',
    coordinates: { lat: 34.722393, lon: 32.471802 },
  },
  {
    id: 'pinarbashi',
    name: 'Pinarbashi',
    displayName: 'Pinarbashi',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Pinarbashi',
    coordinates: { lat: 35.278335, lon: 33.267014 },
  },
  {
    id: 'ruwayshid',
    name: 'Ruwayshid',
    displayName: 'Ruwayshid',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Ruwayshid',
    coordinates: { lat: 32.403696, lon: 39.142216 },
  },
  {
    id: 'sanliurfa',
    name: 'Sanliurfa',
    displayName: 'Sanliurfa',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Sanliurfa',
    coordinates: { lat: 37.460456, lon: 38.912852 },
  },
  {
    id: 'tabqa',
    name: 'Tabqa',
    displayName: 'Tabqa',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Tabqa',
    coordinates: { lat: 35.755614, lon: 38.551251 },
  },
  {
    id: 'tal-siman',
    name: 'Tal Siman',
    displayName: 'Tal Siman',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: false,
    csvPrefix: 'Tal_Siman',
    coordinates: { lat: 36.263473, lon: 38.924055 },
  },
  {
    id: 'tel-nof',
    name: 'Tel Nof',
    displayName: 'Tel Nof',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    herculesBase: true,
    csvPrefix: 'Tel_Nof',
    coordinates: { lat: 31.829716, lon: 34.837949 },
  },
  {
    id: 'carrier-1',
    name: 'carrier_group',
    displayName: 'Carrier Group',
    icao: '',
    isMainBase: false,
    isHeliport: false,
    isCarrier: true,
    herculesBase: false,
    csvPrefix: 'CARRIER',
    coordinates: { lat: 35.435000, lon: 35.596667 },
  },
  {
    id: 'kharab-ishk',
    name: 'Kharab Ishk',
    displayName: 'Kharab Ishk',
    icao: '',
    isMainBase: false,
    isHeliport: true,
    herculesBase: false,
    csvPrefix: 'Kharab_Ishk',
    coordinates: { lat: 36.546867, lon: 38.587486 },
  },
  {
    id: 'lakatamia',
    name: 'Lakatamia',
    displayName: 'Lakatamia',
    icao: '',
    isMainBase: false,
    isHeliport: true,
    herculesBase: false,
    csvPrefix: 'Lakatamia',
    coordinates: { lat: 35.106312, lon: 33.321671 },
  },
  {
    id: 'marj-as-sultan-north',
    name: 'Marj as Sultan North',
    displayName: 'Marj as Sultan North',
    icao: '',
    isMainBase: false,
    isHeliport: true,
    herculesBase: false,
    csvPrefix: 'Marj_as_Sultan_North',
    coordinates: { lat: 33.500423, lon: 36.466322 },
  },
  {
    id: 'marj-as-sultan-south',
    name: 'Marj as Sultan South',
    displayName: 'Marj as Sultan South',
    icao: '',
    isMainBase: false,
    isHeliport: true,
    herculesBase: false,
    csvPrefix: 'Marj_as_Sultan_South',
    coordinates: { lat: 33.487476, lon: 36.474471 },
  },
  {
    id: 'naqoura',
    name: 'Naqoura',
    displayName: 'Naqoura',
    icao: '',
    isMainBase: false,
    isHeliport: true,
    herculesBase: false,
    csvPrefix: 'Naqoura',
    coordinates: { lat: 33.107906, lon: 35.127285 },
  },
  {
    id: 'qabr-as-sitt',
    name: 'Qabr as Sitt',
    displayName: 'Qabr as Sitt',
    icao: '',
    isMainBase: false,
    isHeliport: true,
    herculesBase: false,
    csvPrefix: 'Qabr_as_Sitt',
    coordinates: { lat: 33.458595, lon: 36.356859 },
  },
  {
    id: 'taftanaz',
    name: 'Taftanaz',
    displayName: 'Taftanaz',
    icao: '',
    isMainBase: false,
    isHeliport: true,
    herculesBase: false,
    csvPrefix: 'Taftanaz',
    coordinates: { lat: 35.973223, lon: 36.785894 },
  },
];

/**
 * Get airport by ID
 */
export function getAirportById(id) {
  return airports.find(airport => airport.id === id);
}

/**
 * Get main base airport
 */
export function getMainBase() {
  return airports.find(airport => airport.isMainBase);
}

export default airports;
